### ISSUE TITLE
Mobile Safari (iOS 7): Disabled Input Elements are transparent

### ISSUE THREAD

**Issue by hojerst** [necolas/normalize.css#261]
On iOS 7, disabled input elements are transparent (opacity: 0.4). imho this should be normalized to opacity: 1.0 as this is the case in most other browsers.

**Comment by shrpne** [comment]
@necolas how about to document these inconsistencies [somewhere](https://github.com/necolas/normalize.css#extended-details-and-known-issues)? I think users should know, that normalize.css does not cover all cases.
