### ISSUE TITLE
DL not normalized

### ISSUE THREAD

**Issue by Merri** [necolas/normalize.css#325]
Firefox / Gecko does not add margin to DL element if it is inside a list. This means there is a rendering difference between Firefox and other browsers.

Compare rendering of http://codepen.io/Merri/pen/zchxA

**Comment by jonathantneal** [comment]
@battaglr, this would be one to look into, time permitting.

**Comment by battaglr** [comment]
@jonathantneal, I'll take a look!

**Comment by jonathantneal** [comment]
I’m not seeing any differences in Chrome 30/49, Firefox 30/45, IE8-11, Edge, or Safari 6.2-9, Android 

http://s.codepen.io/jonneal/debug/dd0c888cb9486acd7f0468aaed59d297
