### ISSUE TITLE
Forms items inherit text color while background stays the same.

### ISSUE THREAD

**Issue by victor-yarema** [necolas/normalize.css#339]
Commit 0b5badd591e63b1dcc914a2479f681b9297e6514 fixed issue gh-157.
After that forms items inherit text color while background stays the same.
Before that all text in forms items always had adequate text and bg colors contrast from user agents default styles.
Now if we specify white text on black background for ancestor we will be able to read simple text but unable to see text in forms.
Test: http://codepen.io/anon/pen/FyhsL (forked from http://codepen.io/mattbrundage/pen/hFHoi).
Proposed solution: simply specify some color explicitly, e.g. "color: black;".
General proposal for further changes: text color should be modified with background to ensure that it doesn't break readability.

**Comment by raphaelgoetter** [comment]
Yep, have the same problem since I use normalize :(

**Comment by battaglr** [comment]
IMHO, if you want that your form elements to have a certain color, you should explicitly declare it, and don't trust on defaults. If you do, [this kind of things could happen](https://github.com/openstreetmap/openstreetmap-website/pull/883).

There's already some discussions about this on #414.

**Comment by brendon** [comment]
I agree, removing `colour: inherit` would make more sense. I think it's safer to allow the browser and operating system to set reasonable defaults.

**Comment by jonathantneal** [comment]
This has been resolved by #502.

**Comment by brendon** [comment]
Excellent!
