### ISSUE TITLE
Can we have minified copies in Releases (not Repo)?

### ISSUE THREAD

**Issue by whz-pa** [necolas/normalize.css#352]
The 'Releases' feature, adds support for hosting builds and binaries of a version (manually or tag-driven).
So, is there any plan for adding a minified version during a release?

**Comment by p4bloch** [comment]
To provide an actual answer to this question instead of making assumptions on everyone else's setup, the CDN already provides a minified version for this library
https://cdnjs.com/libraries/normalize
