### ISSUE TITLE
`table`'s minor improvement

### ISSUE THREAD

**Issue by 7studio** [necolas/normalize.css#354]
Hi nicolas,

Just in case, you don't need to normalise the `border-spacing` CSS property because this property applies only when `border-collapse` is `separate`.
cf.: https://developer.mozilla.org/en-US/docs/Web/CSS/border-spacing

**Comment by 7studio** [comment]
I didn't find this issue before opening mine :disappointed: 
But I don't totally agree with [this comment](https://github.com/necolas/normalize.css/issues/165#issuecomment-32430161). IMHO, if a component switches to `separate`, it's its job to redefine `border-spacing` and not to normalize.css to prevent it. In many cases, if you change `border-spacing`, it is not to specify a `0` distance between the borders of adjacent cells.
Maybe I should close this issue :confused:

**Comment by battaglr** [comment]
I totally agree with you: if you want a value of  `separate` it sure wouldn't be with a value of `0`.

To be clear: your argument is valid if we take into consideration the objective of `normalize.css`... but if we were talking about a "normal `reset`", then [this comment](https://github.com/necolas/normalize.css/issues/165#issuecomment-32430161) makes total sense.

It's just a matter of focus. Hope I was clear enough —not that awake right now :sweat:.

**Comment by jonathantneal** [comment]
The additional table styles will probably be removed in v4, unless they are actually normalizing browser behavior. If they are opinionated defaults, they can live in [Sanitize.css](https://github.com/10up/sanitize.css) or [Bootstrap](https://github.com/twbs/bootstrap).

**Comment by battaglr** [comment]
This issue should be considered resolved by 02c5c7adbbec1707900fde86068405735c733b42.
