### ISSUE TITLE
Search inputs apperance property

### ISSUE THREAD

**Issue by chris-pearce** [necolas/normalize.css#360]
`-webkit-appearance: textfield;` doesn't remove the oversized rounded corners from iOS devices:

![screen shot 2014-08-13 at 11 23 38 am](https://cloud.githubusercontent.com/assets/1342772/3900235/841e9a3c-2288-11e4-862d-12b639827248.png)

Is this intentional? As for every project I have to set: `-webkit-appearance: none;` to remove the rounded corners.

**Comment by cvrebert** [comment]
@jonathantneal Close per https://github.com/necolas/normalize.css/issues/260#issuecomment-33253436 ?

**Comment by jonathantneal** [comment]
Yes, Normalize.css can’t reasonably fix this without redefining page and form styles, which is something we [avoid](https://github.com/necolas/normalize.css/pull/502#issuecomment-173964198). Therefore, this styling should be handled in components.
