### ISSUE TITLE
Subscript and Superscript fail on writing-mode:vertical-rl

### ISSUE THREAD

**Issue by rasamassen** [necolas/normalize.css#366]
If &lt;sub&gt; or &lt;sup&gt; are set and the writing-mode is -webkit-writing-mode:vertical-rl; -ms-writing-mode:tb-rl; writing-mode:vertical-rl;  (or lr), then the positioning fails.

**Comment by necolas** [comment]
Please could you include a reduced test case to demonstrate the default behaviour and the problem when normalize.css is used.

**Comment by jonathantneal** [comment]
@rasamassen, is this still an issue for you? If not, I will be closing this issue.

**Comment by jonathantneal** [comment]
This appears to have been a WebKit bug that may have been resolved sometime since 2013. I’m closing this, but feel free to open a new issue if this affects you in the future.
