### ISSUE TITLE
[role="button"] should be styled with cursor:pointer

### ISSUE THREAD

**Issue by thierryk** [necolas/normalize.css#371]
At the very least, [role="button"] should be styled with `cursor: pointer`, but I think it would make sense to style other elements the same way, for example:

```
[role="button"],
button,
input,
label,
select {
    cursor: pointer;
}
```

If `menu` was considered in nomalize, then we could also add `menuitem`in there.

**Comment by necolas** [comment]
Yes let's remove some of the opinionated styles instead.

**Comment by EE31** [comment]
`<style>
  .cell {cursor: grab;}
 </style>
 <input type="text" class="grab" value="Se connecter" onclick="window.open('https://github.com', '_blank', 'toolbar=yes,scrollbars=yes,resizable=yes,top=100,left=100,width=1000,height=550')">`

**Comment by garrettw** [comment]
Please don't spam.
