### ISSUE TITLE
[type="submit"] and button line-height

### ISSUE THREAD

**Issue by esseswann** [necolas/normalize.css#377]
Buttons inherit line-height while inputs don't. Had to change 323 line to 
<code>
input {
  line-height: inherit;
}
</code>
Is it OK?

**Comment by ArmorDarks** [comment]
I might be wrong, but it seems that `line-height: inherit;` is now default behavior for Firefox 34.0.5 and Opera 12.1, while Chrome using it's own predefined line-height (probably `normal`)

**Comment by cvrebert** [comment]
Yes, Chrome's UA stylesheet sets `line-height: normal` for `input`s (as of Chrome 48 anyway):
<img width="438" alt="ua-chrome" src="https://cloud.githubusercontent.com/assets/419884/12528125/2f078356-c142-11e5-964f-b91da320f755.png">

**Comment by cvrebert** [comment]
Firefox 45 also sets `line-height: normal` (not `inherit`) for `input`s:
<img width="535" alt="ff" src="https://cloud.githubusercontent.com/assets/419884/12528146/e6207d9a-c142-11e5-96e6-dbc849044469.png">

**Comment by jonathantneal** [comment]
@cvrebert, does this mean the fix normalizes behavior on older versions of Firefox and Chrome now? Do you have a way to test? If not, let me know and I will.

**Comment by cvrebert** [comment]
Ditto for Safari 9.0.3:
<img width="304" alt="saf" src="https://cloud.githubusercontent.com/assets/419884/12528538/a62da53a-c14e-11e5-85bb-70088c0ec16d.png">

**Comment by cvrebert** [comment]
@jonathantneal https://github.com/necolas/normalize.css/blob/5daad010a2f19c12b89f317ba9d2c8e4573210d7/normalize.css#L328-L335 already normalizes this (albeit for different reasons).

**Comment by jonathantneal** [comment]
The `line-height` issue was resolved in Firefox 30, so this normalization may be dropped.
