### ISSUE TITLE
<dialog open></dialog>

### ISSUE THREAD

**Issue by sylvain-** [necolas/normalize.css#389]
dialog{
display:block;
}

dialog:not([open]) {
display: none;
}

dialog::backdrop {
position: fixed;
top: 0;
right: 0;
bottom: 0;
left: 0;
background: rgba(0, 0, 0, .01);
}

**Comment by cvrebert** [comment]
`:not()` isn't supported in IE8 (which Normalize supports), so you'll need to rework that part.

**Comment by sylvain-** [comment]
dialog{display:none}
dialog[open]{display:block}

**Comment by necolas** [comment]
I'll accept a pull request that includes an entry in the test file and some indication of browser testing.
