### ISSUE TITLE
Set font-family to the BODY instead of the HTML

### ISSUE THREAD

**Issue by BeSite** [necolas/normalize.css#404]
Wouldn't it make more sense to set stuff like `font-family` to the BODY instead of the HTML?

I ran into this issue because the WordPress editor CSS sets a font-family to the BODY, overriding the font-family set to the HTML.

**Comment by necolas** [comment]
that sounds like the intention. this is meant to be overridden by app `html` or `body` font

**Comment by BReduardokramer** [comment]
Hi.  that sounds like the intention. this is meant to be overridden by app
html or body font.
Em 14/01/2015 10:53, "BeSite B.V." <notifications@github.com> escreveu:
