### ISSUE TITLE
v1 can not be installed npm

### ISSUE THREAD

**Issue by sugarshin** [necolas/normalize.css#407]
Version 1~ can not be installed by npm.
Please put the tag.

**Comment by MoOx** [comment]
Meanwhile `npm i git://github.com/necolas/normalize.css.git#v1.1.1`

**Comment by sugarshin** [comment]
@MoOx can not install.

**Comment by MoOx** [comment]
Ha. v1 probably doesn't have a package.json. You should use `napa` to get this one.

**Comment by kud** [comment]
https://github.com/necolas/normalize.css/tree/v1

Indeed, no `package.json`. Use https://github.com/shama/napa

**Comment by sugarshin** [comment]
@MoOx @kud Been resolved. Thank you!!
