### ISSUE TITLE
git.io/normalize - No url found for normalize

### ISSUE THREAD

**Issue by kaatt** [necolas/normalize.css#411]
http://git.io/normalize doesn't work any longer. It says
>No url found for normalize

**Comment by ryanswedal** [comment]
I just noticed this too.

**Comment by necolas** [comment]
git.io seems broken. no idea why they have killed the short url for normalize.css (cc @mdo)

these instructions (inc. `code`) don't let you make a custom url – https://github.com/blog/985-git-io-github-url-shortener

**Comment by mdo** [comment]
No idea what's up either. I'm out of the office right now, but if you could ping the Support team (email support@github.com or use the contact page), that'd probably help get more folks looking at the git.io stuff. Apologies for the hiccup though!

**Comment by necolas** [comment]
dropping use of git.io. future versions will link to this repo
