### ISSUE TITLE
Set normalized styles for different appearance default styles

### ISSUE THREAD

**Issue by ximex** [necolas/normalize.css#414]
The browsers takes different styles from the different operation systems.
Like in Ubuntu Gnome, you could choose between a light and a dark theme. in the dark theme all input, textarea, select, ... elements have dark background colors, that are normaly white.

the solutions will look something like:

input, textarea, select {
  color: #000000;
  background-color: #ffffff;
}

here is an example: https://github.com/openstreetmap/openstreetmap-website/pull/883

**Comment by anEffingChamp** [comment]
I think that setting variants of a browser reset contradicts the goal of a reset, which is standardizing behavior, and appearance. If a web browser wants to dynamically recolor elements then that is their prerogative, but this project is not the place for that.

**Comment by digitalcrusade** [comment]
Agree with @anEffingChamp Normalize is designed to standardise behaviour and layout across browsers, it is not designed for browser customization IMO.

**Comment by Yeswanth-JG** [comment]
@ximex ...Here normalization relates only to the 'Standardization' of the basic logical display of the tags across all browsers consistently.
@digitalcrusade is right...!

**Comment by battaglr** [comment]
IMHO those styles belong in your own project, not in `normalize.css`. You can see previous discussions on [this comment](https://github.com/necolas/normalize.css/issues/126#issuecomment-32493842) from #126, #207, and #174.

Hope it helps.

**Comment by necolas** [comment]
I agree with the comments above. If anything, I'd like to reduce the amount of code in normalize.css and undo some of the more arbitrary style choices.
