### ISSUE TITLE
Normalize font-size

### ISSUE THREAD

**Issue by dkompras** [necolas/normalize.css#416]
Good day:
I find nothing on this subject.
I suggest adding the following code:
"html {font-size: 62.5%;}"
Simplifies use of font-size throughout the document.
Description normalize font-size to 10px.
When setting font-size to 10px, provides that in all actions of the elements can easily configure both em and%. To satisfy recommendation http://www.w3.org/TR/WCAG10-CSS-TECHS/.
Examples:
1 em is equal to 100% is equal to 10 px.
1.25 em is equal to 125% is equal to 12.5 px.
Sincerely Manuel R. Castro Iglesias dkompras@gmail.com

Translated to English with google translate from Spanish.

Buen día:
No encuentro nada sobre este tema.
Sugiero añadir el siguiente código:
"html {font-size: 62.5%;} "
Simplifica el uso de font-size en todo el documento.
Descripción normalizar font-size a 10px.
Al fijar font-size a 10px, facilita que en todas las medidas de los elementos se puedan configurar de manera sencilla tanto en em como en %. Para cumplir la recomendación http://www.w3.org/TR/WCAG10-CSS-TECHS/.
Ejemplos:
1 em es igual a 100% es igual a 10 px.
1,25 em es igual a 125%  es igual a 12,5 px.
Atentamente Manuel R. Castro Iglesias dkompras@gmail.com

Traducido al inglés con google translate desde español.

**Comment by florianbouvot** [comment]
There is a lot of article and blog post that speak about that : [How we learned to leave default font-size alone and embrace the em by @filamentgroup](http://www.filamentgroup.com/lab/how-we-learned-to-leave-body-font-size-alone.html).

**Comment by sean1138** [comment]
Desktop browsers default to 16px for the default font size and I think the normalize project is not about changing something like that.  

The method of setting 1em = 10px has always made me cringe.  When I started using em values I did a lot of reading about typography and readability philosophies (https://ia.net/know-how/100e2r probably being my favorite opinion on the matter) and never once did it occur to me that I should make 100%/1em be something unreadable.  Body copy should be 100%, header copy larger, some less important things smaller.  I came away with my own philosophy that 100%=16px=1em is just fine and that I should work with that idea rather than against it.  To have my pixel values (for non-text things) harmonious with the text content is not that hard, just go with multiples of 8 instead of 10.

**Comment by battaglr** [comment]
@dkompras: Although some may find that approach useful, I'm almost sure that this doesn't fit in the Normalize scope. *Spanish: aunque algunos puedan encontrar útil esta metodología, no creo que esto esté alineado con la filosofía de Normalize.*

:-1:

**Comment by anEffingChamp** [comment]
I agree with Sean. Although the base 10 mathematics are more intuitive
for most of us, eventually we will want the majority of the page
content to be 1em. Greater typographic minds than ours have researched
what is most appropriate for the most people, and decided on a default
font size.

With that said, you are welcome to alter font sizes however you like.
It is just not a useful default unless it is able to trump the
research science that has already gone into the current one.

**Comment by dkompras** [comment]
I appreciate all your kind attention and prompt reply.
I understand the position that you all share.
I recognize that the standard measure of font-size = 16px, must be correct for compatibility, and should be the standard size "body element".
Since I'm not a programmer, I know what is effect on media query, I'll find more information on this subject.
But I have understood that the media query, informing me of the width and height of the screen px, and the density of points. In any case the calculations with a 10px font-size are simplified, provided that in the end the measures are reinstated in the font-size to 16px or 100%. And be all measurements in em and%, these measures maintain their share.
The experts, like you, they will be easy to work with calculations in base 8 or Base16, this would indeed be the correct base, but the rest of us find it easier to work in base 10.
The question raised did not involve modifying normalize, if I gave it to understand, I apologize.
Thanks again to everyone.
How the hell closes a comment, you are adequately answered?
