### ISSUE TITLE
Sub or Sup text decoration isn't aligned with normal text

### ISSUE THREAD

**Issue by Situphen** [necolas/normalize.css#417]
When you use `<sup>` or `<sub>` in a link, the text decoration isn't aligned with the rest of the text. Normaly, it should be. It's caused by https://github.com/necolas/normalize.css/blob/master/normalize.css#L158. Is there a way to fix this ?

**Comment by Ogien** [comment]
Are you referring to this? http://codepen.io/Ogien/pen/KwEyRK

**Comment by Ogien** [comment]
```
/* This creates the same margins as a P tag */
a{
  display: inline-block;
  margin: 1em 0;
}

/* CSS4 Only :( */
$* > a{ margin: 0; }

```
That would be how I would get it to work. Nothing in CSS3 right now that can fix this unless you use JQuery.

**Comment by necolas** [comment]
Please can you create a reduced test case to demonstrate the problem and expectation.

**Comment by jonathantneal** [comment]
@Situphen, the default font size and vertical alignment of `<sup>` and `<sub>` elements also cause text-decoration to shift up and down. This is not unique to normalize.css.
