### ISSUE TITLE
-webkit-padding-start: 0px;

### ISSUE THREAD

**Issue by atilkan** [necolas/normalize.css#420]
This should be added with proper prefixes.. UL element's default.
-webkit-padding-start: 0px;

**Comment by ramasilveyra** [comment]
padding: 0; is the same and it's valid.

**Comment by atilkan** [comment]
Correct. But until the specs finishes (dream on) this prefixes should be added. Otherwise i can say, it doesn't do the job.

**Comment by necolas** [comment]
Your suggestion isn't necessary as the existing padding properties work too.

**Comment by atilkan** [comment]
No, It doesn't work.

**Comment by battaglr** [comment]
@atilkan: not explaining on detail, providing reduced use-cases, or documentation to back up your claims, makes any modification/addition request to weak to consider. Just an advice.

**Comment by atilkan** [comment]
@battaglr yes, it is just an advice.
