### ISSUE TITLE
button focus outline?

### ISSUE THREAD

**Issue by khanh** [necolas/normalize.css#424]
chrome like to add ugly blue outline to buttons:

http://jsfiddle.net/u4pXu/

I needed to add the following css at the bottom for happiness

button:active {
outline: none;
border: none;
}

button:focus {outline:0;}.

**Comment by Yeswanth-JG** [comment]
@khanh 
> First thing, Normalize.css will stabalize the tags display to a standardized way. It doesn't deal with any optimization.

Outline is a property meant for accessibility. Normalize wont handle this.
Border usage depends on the websites. Removing it is not the global issue.

**Comment by necolas** [comment]
Outline style is a browser- or application-level concern. But keeping the browser defaults, the module avoids causing accessibility issues.

**Comment by khanh** [comment]
ahh, gotcha, thanks for the clarification :)
