### ISSUE TITLE
Publish latest to NPM

### ISSUE THREAD

**Issue by tshaddix** [necolas/normalize.css#425]
Hello!

Saw the issue with `main` was fixed in the `package.json`: [commit](https://github.com/necolas/normalize.css/commit/947b1ae124cc987848262b6513242c83348a733d)

Any chance of an `npm publish` in the near future so we can make use of this?

Thanks!

**Comment by necolas** [comment]
will be published today

**Comment by tshaddix** [comment]
@necolas Thanks!
