### ISSUE TITLE
img{display:block;}?

### ISSUE THREAD

**Issue by Schweinepriester** [necolas/normalize.css#426]
saw #54 but no other mention:

was

```css
img {
 display: block;
}
```

already discussed?
if so, please point me to it
if not: feature request(ed) :)

**Comment by sullinger** [comment]
Hi Kai,

the img element is an inline element (see the W3C specs) and I don't know any browser that treats it otherwise.
Please keep in mind that normalize.css is not a reset.

Because of this, I have to vote against this feature request.
Thanks for your interest in improvement, though!

Stefan

**Comment by battaglr** [comment]
I agree with @sullinger.

:-1: 

Would be great to find a solution for that "problem", though.

**Comment by LukeAskew** [comment]
```css
img {
  display: inherit;
}
```

**Comment by FagnerMartinsBrack** [comment]
> Would be great to find a solution for that "problem", though.

@battaglr Which "problem" are u refering to?

**Comment by necolas** [comment]
yep, images are not block by default

**Comment by battaglr** [comment]
> Which "problem" are u referring to?

@FagnerMartinsBrack: to the one that originated the PR #54, the extra space at the bottom of `<img>` elements. And the quotes around "problem" are because "that extra space" it's the normal behaviour, but usually not the desired one.

**Comment by FagnerMartinsBrack** [comment]
@battaglr Thanks for the enlightenment, I just asked because it seems useful to link cross-referenced discussions for posterity.

**Comment by digitalcrusade** [comment]
@battaglr so am I right in thinking you are suggesting to add display: block to the img element to avoid the extra space at the bottom? If so I can see your point, and in general would be useful but I also feel that the problem would be that the img would then not display as originally intended and could be classed as 'customised' and therefore not suitable for Normalize. Catch 22 really.

**Comment by battaglr** [comment]
> am I right in thinking you are suggesting to add display: block to the img element

@digitalcrusade: nope, I never said that. :/

**Comment by digitalcrusade** [comment]
@battaglr apologies, wasn't sure.

**Comment by battaglr** [comment]
@digitalcrusade: no need to apologize. :)

**Comment by BReduardokramer** [comment]
OK. I will check it soon. Thank you!
Em 19/03/2015 21:59, "Kai" <notifications@github.com> escreveu:

**Comment by Schweinepriester** [comment]
another suggestion is

```css
img {
 vertical-align: middle;
}
```

see e.g. <https://github.com/bendc/frontend-guidelines#flow>

maybe it could be controlled via e.g.

```css
a img {
 vertical-align: middle;
}
```

?
since if a `<img>` is inside `<a>`, the positioning will always (?) happen through the `<a>`?
