### ISSUE TITLE
Remove margin from figure

### ISSUE THREAD

**Issue by corysimmons** [necolas/normalize.css#427]
Trips me up so often and it's totally unexpected/specific to `figure`. Gross :-1:

**Comment by corysimmons** [comment]
Weekbump :8ball:

**Comment by corysimmons** [comment]
3weekbump :palm_tree:

**Comment by corysimmons** [comment]
It's also weird that `h1` have a specific margin on them as well.

**Comment by joshvickerson** [comment]
Is this behavior different across browsers? As the aim of this project is to simply make things more consistent, resetting a common default may not be a good fit for Normalize.

**Comment by corysimmons** [comment]
![](http://i.imgur.com/ZFpWAx7.png)

Bah I suppose it is. Damn W3C cherrypicking a couple random elements to apply ugly margins to. :(
