### ISSUE TITLE
Possible type for `template` tag

### ISSUE THREAD

**Issue by whitneyit** [necolas/normalize.css#429]
On line [#74](https://github.com/necolas/normalize.css/blob/0c31dada5189a577f16fc61cbd8680e7f35bcca3/normalize.css#L74) the following code is present.

> Hide the `template` element in IE 8/9/11, Safari, and Firefox < 22.

Is this supposed to be

```diff
-Hide the `template` element in IE 8/9/11, Safari, and Firefox < 22.
+Hide the `template` element in IE 8/9/10, Safari, and Firefox < 22.
```

**Comment by necolas** [comment]
I don't understand the question

**Comment by sullinger** [comment]
I think the question is: Is it "IE 8/9/**10**" or "IE 8/9/**11**"?

**Comment by necolas** [comment]
ah, thanks. fixed

**Comment by whitneyit** [comment]
Sorry for the ambiguity. That was the question. Maybe I will just send a PR next time
