### ISSUE TITLE
Set max-height for img, responsive background

### ISSUE THREAD

**Issue by bueltge** [necolas/normalize.css#436]
Thanks for share this helpful normalize stylesheet.
Currently I use as helpful to set the `img` tag to a `max-height: 90vh`. This help me to remove problems with bug images in different screen. Maybe the other inside the team here see this also as helpful for normalize I can add a pull request.
Best

**Comment by bartveneman** [comment]
Seems more like a nice-to-have boilerplate default than a browser inconsistency, therefore it might not be suitable for this repository. But I like the idea.

**Comment by necolas** [comment]
The suggestion is not suitable for this project because it is not a browser default, or a fix for a common issue.

**Comment by bueltge** [comment]
Understandable, thx for this hint.
