### ISSUE TITLE
hgroup is no longer a valid html5 specs element

### ISSUE THREAD

**Issue by cheahkhing** [necolas/normalize.css#439]
Hi, as title, do we still want it to be in the stylesheet? I asked because my editor highlight it as an error.

**Comment by Florian-R** [comment]
gh-437

**Comment by battaglr** [comment]
@cheahkhing: hi! please [see this](https://github.com/necolas/normalize.css/search?q=hgroup&type=Issues&utf8=%E2%9C%93).

**Comment by cheahkhing** [comment]
hi, guys, thanks for pointing me to the comments. forgive me for not searching first and asked.
But yet, after so many requests on removing, it is still being kept for supporting those sites that using obsolete tags? I still don't get it.

**Comment by Florian-R** [comment]
@cheahkhing See this comment : https://github.com/necolas/normalize.css/pull/180#issuecomment-16005485

**Comment by cheahkhing** [comment]
Hi, thanks again for the references, since the owner doesn't want to exclude that, i'll just close this and manually remove it from my usage. Thanks.
