### ISSUE TITLE
Make package.json compatible with tools like parcelify

### ISSUE THREAD

**Issue by jholster** [necolas/normalize.css#441]
The package.json defines normalize.css as main entry point. This breaks compatibility with tools like parcelify which rely on require("normalize.css") to parse the dependency tree (in order to include the style files). The official NPM documentation also suggests that the "main" script should be require'able: https://docs.npmjs.com/files/package.json#main

I suggest that 'main' points to empty index.js file.

**Comment by nmalaguti** [comment]
:+1:

**Comment by TrySound** [comment]
:-1: I like to use postcss-import and `@import 'normalize.css';`

**Comment by domachine** [comment]
:+1:

**Comment by jonathantneal** [comment]
![Why not both](https://33.media.tumblr.com/0ae4a458b02b1705c96dd846493e2aad/tumblr_inline_n3ghj9J3u91qcklud.gif)

Can we have both?

@jholster, what would you expect or what might you suggest the primary entry point be in a CSS Library?

@TrySound, hey, good to see you here! Thanks for all you do in open source. If the [main key](https://github.com/necolas/normalize.css/blob/2bdda84272650aedfb45d8abe11a6d177933a803/package.json#L15) changes, would that cause your import to stop working? Could [files](https://github.com/necolas/normalize.css/blob/2bdda84272650aedfb45d8abe11a6d177933a803/package.json#L6-L9) determine this?

**Comment by TrySound** [comment]
@jonathantneal Nope. `style` field is checked first.

**Comment by TrySound** [comment]
But making empty index.js seems hacky.

**Comment by cvrebert** [comment]
> But making empty index.js seems hackish.

Yes, might as well omit `main` instead if that route were chosen.

**Comment by jonathantneal** [comment]
@TrySound, may `main` be safely removed as @cvrebert suggests or is this issue fully resolved as-is?

**Comment by jonathantneal** [comment]
Spoke with Bogdan and will be removing `main` in the v4 PR.

> [The] style field is checked first and if no `main` [is found then] it will look for index.css. So everything is okay.
