### ISSUE TITLE
input[attr] specificity

### ISSUE THREAD

**Issue by matthewlein** [necolas/normalize.css#442]
Hello,

Wondering if normalize can drop the input qualifiers for the inputs with attributes? As it is now, `input[type="checkbox"]` is more specific than a single class, so it can't be overridden with a class, whereas `[type="checkbox"]` is not. It should accomplish the same thing with less specificity, right?

My specific use case is overriding 0 padding on a checkbox from this:
https://github.com/necolas/normalize.css/blob/2bdda84272650aedfb45d8abe11a6d177933a803/normalize.css#L334-L338

**Comment by matthewlein** [comment]
I know padding on a checkbox input isn't super valuable (or even works in most browsers), but the overall idea might be...

**Comment by battaglr** [comment]
There's already a discussion in an issue (#187) that I opened a while ago.

*Sadly I deviated the topic —and FWIW I have changed my mind since then—, but could be useful as a reference*. Hope it helps.

**Comment by matthewlein** [comment]
Oh, I didn't find it in my searches. That pretty well covers it...its a pretty weak use case. Personally I have no problem editing my file if I need it.

**Comment by jonathantneal** [comment]
Following the threads, it seems it was decided that the potential performance impact was not worth the reduced selector weight. I might have leaned the other way, but any moderate developer should catch this if it ever creates a problem for them.

**Comment by battaglr** [comment]
While I strongly believe that libraries shouldn't have —or should try to avoid as much as possible— selectors with a specificity higher than `[0,0,1,0]`, in this case —and considering the current code-base— I agree that considering the performance impact that this would have is not really worth it to reduce the specificity.
