### ISSUE TITLE
Official Sass Support

### ISSUE THREAD

**Issue by TheJaredWilcurt** [necolas/normalize.css#446]
I don't know if Normalize has already been ported to Sass/SCSS, but it's not mentioned in the readme.

I did a quick convert for my own project of 3.0.3. Feel free to merge it into the repo.

* https://gist.github.com/TheJaredWilcurt/7594dbd92c3c2e22256e

**Comment by florianbouvot** [comment]
Please see #9, #22, #26, #30, #240

**Comment by svenjuhnke** [comment]
Porting CSS to SCSS? Isn't it upside down?

Vice versa. SCSS as masterfile.

**Comment by TheJaredWilcurt** [comment]
@svenjunke That is my feeling as well. Just make one normalize.sass file and it will automatically create the normalize.css and normalize.min.css for the non-sass users.

**Comment by fleeting** [comment]
I still don't understand the need in this being sass. I get normalize with bower, then have gulp copy it as normalize.scss, which is then compiled with my sass files. You could also just have your build process combine normalize.css with your css instead.

I guess I'm just missing the need for this besides having it in sass, just to have it in sass.

**Comment by florianbouvot** [comment]
@fleeting +1
We don't need Sass version, Sass is CSS compatible so you can create your own build process.

**Comment by stevendchen** [comment]
from necolas: 
> "Thanks for taking the time to do this. There have been a couple of pull requests related to Sass versions of the file, but I'd rather not have to maintain 2 near-identical files. I'm happy to either let people Sass-ify the file themselves or have others maintain a Sass version."

if you'd really like there's:
https://github.com/esses/normalize.sass

and 
https://github.com/JohnAlbin/normalize-scss
https://github.com/guerrero/normalize.scss

but as @fleeting said, if you're using gulp or the like you can just stick it in to your build as css

**Comment by necolas** [comment]
I still don't see why this would be a good thing to do :)
