### ISSUE TITLE
Inconsistent textarea rendering in IE11 and Chrome 42, Opera 29

### ISSUE THREAD

**Issue by Shakil-Shahadat** [necolas/normalize.css#447]
Please open this http://jsfiddle.net/radu/RYZUb/ in different browsers. Here is the summery:

1. IE11 has darker border color ( i.e. rgb ( 33, 33, 33 ) ) than chrome, opera and firefox.
2. Bottom margin is not zero chrome 42, opera 29. Setting "vertical-align: top" solves this. See the relevant discussion here http://stackoverflow.com/questions/5196424/inconsistent-textarea-handling-in-browsers. I think you have to undo #280.
3. In addition to the above fiddle, I added normalize.css ver 3.0.3 as the first stylesheet in my local server. Font rendering is different in different browsers. Here is the result in chrome 42, Opera 29, Firefox 37 and IE 11.
![screenshot_5](https://cloud.githubusercontent.com/assets/8978625/7554373/d9a60e7e-f747-11e4-8ae2-1c897ad3fd94.png)

**Comment by jonathantneal** [comment]
@battaglr, if you have time, would you look into this one as well?

**Comment by battaglr** [comment]
@jonathantneal, yes, I will!

**Comment by jonathantneal** [comment]
There are basically no details as to why #280 removed `vertical-align: top` from `textarea`. The [StackOverflow answer](http://stackoverflow.com/a/5196591) notes that adding it back in will resolve this issue. Once further tests confirm this, I’m okay to add it back in.

As this would effectively revert a previous change, I’m also hitting up @mdo @fat @patrickhlauke for any concerns.
