### ISSUE TITLE
Column-count not rendering correctly on chrome

### ISSUE THREAD

**Issue by MrOutput** [necolas/normalize.css#449]
### Also seen here

http://stackoverflow.com/questions/28595742/chrome-bug-content-not-rendering-multi-columns-properly/28618965#comment48539040_28618965

transform: translateZ(0)

I don't know if you can add this to styles with columns or not. Perhaps this would be a conditional mixin with less...

**Comment by cvrebert** [comment]
There are some browser bugs with `translateZ` itself (see e.g. http://bugzil.la/1048279 & http://wkbug.com/138162 from https://github.com/twbs/bootstrap/pull/13649#issuecomment-57767763) and it [creates a new stacking context](http://philipwalton.com/articles/what-no-one-told-you-about-z-index/) (which is often undesirable), so I don't think it's a good general solution.

**Comment by fvsch** [comment]
Browser-specific *rendering* bugs are outside of the scope of normalizing browsers' *default styles*.

This issue should probably be closed.

**Comment by MrOutput** [comment]
@fvsch thanks

**Comment by lhorainemarinas** [comment]
> In any case someone wondering, you can try fixing this by adding this style to child elements
> 
> ```
> -webkit-column-break-inside: avoid;
> -webkit-backface-visibility: hidden;
> ```

you just saved my ass man. thanks!

**Comment by tvld** [comment]
and mine .. ;)))
