### ISSUE TITLE
http://necolas.github.io/normalize.css/

### ISSUE THREAD

**Issue by yanhaijing** [necolas/normalize.css#457]
version is 3.0.3 but site is 3.0.2, update it

**Comment by nicolasmccurdy** [comment]
What if we made the version number dynamic by using a readme badge image or a Jekyll site with a variable for the version? For previous versions we could just link to GitHub's releases page for this repo.

**Comment by yanhaijing** [comment]
good idea

**Comment by nicolasmccurdy** [comment]
Unfortunately it seems like the GitHub release badges on http://shields.io/ don't support periods in repository names. I guess the easiest ways to automate this would be build scripts or client side JavaScript.

**Comment by yanhaijing** [comment]
http://shields.io/ support release，but not support tag, so this way is right.

**Comment by al-the-x** [comment]
FYI, the version number on the website is still 3.0.2, and 3.0.3 has been latest since March? Would you accept a PR for this?

**Comment by necolas** [comment]
Closing as duplicated by #489
