### ISSUE TITLE
Form Margin 

### ISSUE THREAD

**Issue by ppiekarczyk** [necolas/normalize.css#460]
I've noticed something weird in my normalize.css recently. There is nothing that cancels out the random `margin` on my base form element. Is that supposed to be the case? I don't recall that ever being an issue.

**Comment by necolas** [comment]
What browsers have a bottom margin on `form`?

**Comment by ppiekarczyk** [comment]
Close it, I don't remember what the issue was anymore.

**Comment by necolas** [comment]
:)
