### ISSUE TITLE
OSX radios are being clipped in chromium browsers

### ISSUE THREAD

**Issue by josephfusco** [necolas/normalize.css#462]
Chromium browsers clip radio buttons one pixel on the left and bottom if a parent has `overflow:hidden`. This is an [open issue](https://code.google.com/p/chromium/issues/detail?id=396726) with chromium but over a year old. It was brought up in bootstrap but I thought it should be decided on within normalize since it isn't exclusive there.

-----
Radios and checkbox inside container with `overflow:hidden`

<img width="451" alt="overflow-edge" src="https://cloud.githubusercontent.com/assets/6676674/8523930/12ba5062-23c6-11e5-8c8c-46d25d609463.png">

-----

This also can be seen when radios are naturally against the edge of page.

<img width="438" alt="viewport-edge" src="https://cloud.githubusercontent.com/assets/6676674/8523931/16fff7ee-23c6-11e5-8d1b-1fee2045aa67.png">

-----

**[Demo](http://codepen.io/fusco/pen/zGWNRa)**
This would establish a consistency across all operating systems and browsers.

**Comment by walutisme** [comment]
Doesnt happen to me, maybe. Chrome 44.0.2403.61 beta on lubuntu 14.04. From your demo:

![2015-07-07_02 39](https://cloud.githubusercontent.com/assets/10618799/8530138/b9e75034-2451-11e5-82a4-c0b3f690825e.png)

**Comment by cvrebert** [comment]
Per http://crbug.com/396726#c1 , only Mac OS X is affected by this.

**Comment by josephfusco** [comment]
@walutisme This is an OSX only issue as stated in the title. Windows and Linux are fine.

**Comment by jonathantneal** [comment]
I’ve recently started addressing issues here, so forgive me for the delay. I’d like to wait till there is a fix, since the fix involves very opinionated defaults on how radio buttons should align. @josephfusco, thoughts or new info?

**Comment by josephfusco** [comment]
@jonathantneal I have changed my stance on this and agree that it is too opinionated for inclusion in normalize. Since this is a known chromium bug (although the [ticket](https://bugs.chromium.org/p/chromium/issues/detail?id=396726) is approaching 2 years old), developers can simply apply the `1px` shift of the radio input by means of margin, padding, or positioning on the affected side of the element.

**Comment by cvrebert** [comment]
Filed a WebKit bug since this affects Safari too: https://bugs.webkit.org/show_bug.cgi?id=155577
