### ISSUE TITLE
Correct comment

### ISSUE THREAD

**Issue by x4storm** [necolas/normalize.css#463]
In Line 383 and 388, It's set lengend element border to 0. But the comments is describe a color property.

**Comment by fleeting** [comment]
Check out #310. The comment is correct.

**Comment by necolas** [comment]
There's also a bit more info towards the [bottom of the README](https://github.com/necolas/normalize.css/tree/72a77f0316ff55c9a68af22741ca37a1cccb09c4#legend). Although #363 might mean this can be fixed in a less unexpected manner.
