### ISSUE TITLE
Remove -moz-box-sizing

### ISSUE THREAD

**Issue by mzgol** [necolas/normalize.css#466]
Unprefixed `box-sizing` has been available since Firefox 29 which went out a year & 3 months ago; market share of Firefox < 29 is nearly non-existent.

I don't think it's worth keeping the `-moz-box-sizing` version.

**Comment by marcobiedermann** [comment]
@mzgol Take a look at #400

**Comment by mzgol** [comment]
I should have looked at current `master` before reporting. :)
