### ISSUE TITLE
git.io/normalize no longer works

### ISSUE THREAD

**Issue by eksperimental** [necolas/normalize.css#467]
http://git.io/normalize no longer works.
refereces to it should be updated, or contact the github people

**Comment by alrra** [comment]
@eksperimental This was fixed in: https://github.com/necolas/normalize.css/commit/0c31dada5189a577f16fc61cbd8680e7f35bcca3 (see also: https://github.com/necolas/normalize.css/issues/411).

**Comment by eksperimental** [comment]
thank you @alrra
