### ISSUE TITLE
Input text not visible in cases due to color:inherit

### ISSUE THREAD

**Issue by clottes** [necolas/normalize.css#469]
The color:inherit will obviously cause problems if font color is set to something close to white in any section of html.  (Say a header section, etc with a dark background).  Since the font-color becomes inherited, but the background remains default in input elements, it won't look correct or make any sense.  It should NOT be assumed that the user's text in a section of html will not be white or a color close to what happens to be background color of input elements.

button,
input,
optgroup,
select,
textarea {
  color: inherit; /* 1 */
  font: inherit; /* 2 */
  margin: 0; /* 3 */
}

**Comment by clottes** [comment]
color: inherit; /* 1 */ should be removed.

**Comment by CemDemirkartal** [comment]
Absolutely, I dont know who decided this value for color. If that color need to be inherited, then background-color cant stay static as #FFF in original or changed one by developer

**Comment by voronianski** [comment]
@clottes @CemDemirkartal agree that inherit should be removed - https://github.com/necolas/normalize.css/blob/master/normalize.css#L256 /cc @necolas will PR be accepted?

**Comment by cvrebert** [comment]
This was fixed by #502.

**Comment by jonathantneal** [comment]
Thanks, @cvrebert, for spotting this!
