### ISSUE TITLE
abbr tag shows double underline in firefox 40

### ISSUE THREAD

**Issue by hanakin** [necolas/normalize.css#470]
Firefox updated default spec to include a text decoration underline on the abbr which conflicts with the border applied by normalize. suggest setting text-decoration:none on abbr

**Comment by 7studio** [comment]
Duplicate of https://github.com/necolas/normalize.css/pull/451 and https://github.com/necolas/normalize.css/pull/468.

**Comment by cvrebert** [comment]
@jonathantneal Please close as a duplicate?

**Comment by jonathantneal** [comment]
@cvrebert, thanks! Done.
