### ISSUE TITLE
Double font-family - bug or fix?

### ISSUE THREAD

**Issue by WinterSilence** [necolas/normalize.css#476]
`font-family: monospace, monospace;` https://github.com/necolas/normalize.css/blob/master/normalize.css#L233

**Comment by bartveneman** [comment]
It's intentional: https://github.com/necolas/normalize.css/blob/2bdda84272650aedfb45d8abe11a6d177933a803/README.md#extended-details

**Comment by WinterSilence** [comment]
@bartveneman  thanks

**Comment by walterdavis** [comment]
Given the number of times this comes up, do you think that a comment in place (// yes, really! or something like that) would be in order?
