### ISSUE TITLE
I created a wordpress plugin for normalize.css

### ISSUE THREAD

**Issue by CosmicWebServices** [necolas/normalize.css#477]
Can you check out my plugin for normalize.css here https://github.com/ilovecode1/cosmic-normalizer?

**Comment by stefanullinger** [comment]
https://proplugindirectory.com/authors-rating-own-plugins/

How do I know, which version of normalize.css is included in your plugin?

**Comment by CosmicWebServices** [comment]
I am sorry you feel like that about me voting on my own project but, I just wanted to do it.

It uses 3.0.3 so the latest and I do not plan on updating the version.

**Comment by nvartolomei** [comment]
What the point of this plugin?..

**Comment by Toddses** [comment]
You reviewed your own plugin twice?

**Comment by ihorvorotnov** [comment]
+1 What's the point of the plugin?

**Comment by stefanullinger** [comment]
Well – looking at the code, the purpose of this plugin is to add normalize to a WordPress site / frontend.

Thumbs up for creating the plugin. Hope you will improve it and it's README, @CosmicWebServices!

I just think, there is no need to self-review it.

**Comment by nvartolomei** [comment]
@stefanullinger and why would you need to do this via a plugin?

**Comment by stefanullinger** [comment]
@nvartolomei, I won't need a plugin for this, as I have very different workflow. But the WordPress community is huge and I assume that there are some people that are happy about this plugin.

It basically contains the steps neccessary to integrate normalize into a WordPress theme, and if you are writing many themes, this plugin might remove some repetitive tasks. For example, updating normalize in all of your projects could be easily done via a plugin update.

Maybe it is the first plugin from @CosmicWebServices and he learned the basics of writing and publishing WordPress plugins with it, and he is proud of what he created and would like to share his pride with us. And maybe others will have a look at it and learn from it.

Don't get me wrong: I think that this issue/discussion is not the right place to promote the plugin (and this issue can be closed), but I believe that not everything has to have a big benefit for everyone of us. We are all here to explore and share our knowledge, learning from it and creating something even bigger out of it.

**Comment by ihorvorotnov** [comment]
> if you are writing many themes, this plugin might remove some repetitive tasks

In this case, YOU_ARE_DOING_IT_WRONG

> For example, updating normalize in all of your projects could be easily done via a plugin update.

This is completely wrong concept in WP world. A theme must look and work exactly the same for all users right out of the box. Depending on some external plugin for such basic "under the hood" and "low level" stuff is just wrong.

**Comment by stefanullinger** [comment]
> YOU_ARE_DOING_IT_WRONG

There is no *wrong* in this world. You can do it however you like. The only question is: Is it the optimal way, so everyone can work with it.

By the way,
> if you are writing many themes
does not have to mean, that they get published. If you have many clients, you are also writing many themes. And if there is a fix in normalize that all your client's theme should get, you *can* do it via a plugin update. There is nothing wrong with it as long as you and everyone around you are happy with it.
