### ISSUE TITLE
IMG fix

### ISSUE THREAD

**Issue by notiv-nt** [necolas/normalize.css#479]
I think that this code will remove the strange margin-bottom from img 

img {
vertical-align: top or middle or smth;
}

**Comment by Yeswanth-JG** [comment]
It doesnt comes under normalize duty. margin & vertical-align aren't directly related.. Please provide a testcase

**Comment by necolas** [comment]
I'm not sure there's much benefit in changing the default here. I know a lot of people do it just for images, but it's more obvious to `display:block` when you need an element to layout that way.
