### ISSUE TITLE
Add a  normalize-noIE.css for specialized uses

### ISSUE THREAD

**Issue by ppKrauss** [necolas/normalize.css#485]
The proposal [was arrived here](https://github.com/necolas/normalize.css/issues/482#issuecomment-152821599).

[**This adaptation of  Normalize.css, named <i>Normalize-noIE.css</i>**](https://github.com/ppKrauss/normalize-noIE.css), is easy to maintain, removing IE support (cuting ~1/3 of code). Can be used with [web applications](https://en.wikipedia.org/wiki/Web_application) optimized for non-MS browsers, or in production environments where the user has no option to use IE.
 
It is smaller, faster, and will be used in environments where IE not exist.

**Comment by necolas** [comment]
Hi, thanks for the idea. I don't think it is practical from a maintenance perspective, and the file savings over the wire are negligible relative to the total size of all but the sparsely coded website.
