### ISSUE TITLE
Set input[type="search"] box sizing to border-box

### ISSUE THREAD

**Issue by oleersoy** [necolas/normalize.css#486]
Having box-sizing set to `border-box` will it make it consistent with suitcss-base and bootstrap 4.  Both currently reset the box-sizing to `border-box`.

**Comment by patrickhlauke** [comment]
dupe of https://github.com/necolas/normalize.css/issues/471 ?

**Comment by cvrebert** [comment]
This has been fixed by fe567632afcf8afcf17925ab2a507ed87504cce8.

**Comment by jonathantneal** [comment]
Indeed, and #496 was merged. Thanks for pointing that out! Closed.
