### ISSUE TITLE
_support-for.scss missing

### ISSUE THREAD

**Issue by eduardodomingos** [necolas/normalize.css#495]
Compile process fails because _support-for.scss file is missing. In order to fix this I've installed your support-for module gem, and copied the _support-for.scss file into the sass folder. Is there a better way to do this?

**Comment by fleeting** [comment]
This isn't the right repo, looks like you are using a fork with sass support. I believe you are looking for this https://github.com/JohnAlbin/normalize-scss/issues/43.

**Comment by eduardodomingos** [comment]
Thks @fleeting :+1: . Shame on me! Anyway, I've used @catalinux answer on and it´s working. Cheers
