### ISSUE TITLE
Request for collaborators

### ISSUE THREAD

**Issue by necolas** [necolas/normalize.css#500]
Looking to add a couple of people as collaborators / owners. I haven't found the time – or the interest – to adequately manage, verify, test, and fix the open issues and pull requests.

This base code is used in production by tens of millions of sites and apps, meaning that certain kinds of changes need to tested across a large matrix of supported browsers/OS. The Bootstrap team can be a helpful 'dogfooding' partner, as they been when it comes to reporting issues.

/cc @jonathantneal @mdo @fat @patrickhlauke

**Comment by jonathantneal** [comment]
@necolas, I’d love to help again. I follow the issues, but I was hesitant to make calls.

**Comment by necolas** [comment]
Sounds good, thanks

**Comment by patrickhlauke** [comment]
happy to help, though far from being an expert...

**Comment by joelcipriano** [comment]
Sign me up!

**Comment by anselmh** [comment]
I could help to maintain it but would not have the time to be the sole owner of it.

**Comment by mikaspell** [comment]
happy to help, realy

**Comment by necolas** [comment]
Thanks everyone, Jonathan can add people who contribute over time.
