### ISSUE TITLE
Firefox add an extra row in textarea

### ISSUE THREAD

**Issue by SuperPat45** [necolas/normalize.css#505]
Hi,

Firefox add an extra row in textarea when overflow-x is not hidden
To fix this in all browser, we need:
textarea {
	overflow-y: auto;
	overflow-x: hidden;
}

**Comment by cvrebert** [comment]
Does Firefox add this extra row even when the `<textarea>` has a `rows` attribute?

**Comment by SuperPat45** [comment]
yes firefox always add extra row.

**Comment by RachelRVasquez** [comment]
I tried this one on the [test file](http://necolas.github.io/normalize.css/latest/test.html) between Mac's Chrome (V48.0.2564.116) and FF (V43.0.4). It looks like even swapping out the `overflow: auto;` for the suggestion above doesn't make the text areas between the two browsers consistent height wise.

If I had to find the difference between FF and Chrome as to why their heights differ, Chrome has a computed style of 36px on the test file whereas FF's version is 48 if you go by the box model. The box modal paddings between FF/Chrome also differ.

Safari (V8.0.8) has the same computed height as Chrome except the width is different. Not sure if there's a way to "normalize" these elements, but hoping this helps to explain as to why we're seeing the differences.

**Comment by jonathantneal** [comment]
The height of a `<textarea>` is roughly `height: calc(line-height * 2)`. Unfortunately, there’s no way to write this. You would have to explicitly know the line-height. Therefore, we could not normalize the height through normalize.css.
