### ISSUE TITLE
Remove opinionated table reset

### ISSUE THREAD

**Issue by jonathantneal** [necolas/normalize.css#506]
In Normalize v4, [these rules resetting table elements](https://github.com/necolas/normalize.css/blob/v2.1.3/normalize.css#L395-L406) should be removed.

@battaglr recently [created and ran a ton of tests](https://gist.github.com/battaglr/4f7958e26f450da92787) that reveal the table resets in Normalize are opinionated defaults that actually remove the normal behavior consistent in all browsers (from Edge, Chrome, Firefox, Safari, Opera, all the way back to Internet Explorer 6).

Despite the appearance of no space between text in table cells being clearly less readable, we were all hesitant to remove these lines because they’ve just been around for so long (*since Eric Meyer's CSS reset v1, 8 years ago*).

**Comment by jonathantneal** [comment]
Resolved in 02c5c7a

**Comment by battaglr** [comment]
Great! :+1:
