### ISSUE TITLE
Use Normalize.css logo

### ISSUE THREAD

**Issue by jonathantneal** [necolas/normalize.css#509]
@DanielPintilei was kind enough to design a truly sleek and memorable logo after [I made a request on Twitter](https://twitter.com/jon_neal/status/695108990477283328). Normalize.css is probably well enough known not to require any branding, but art is another way we can express the commitment and satisfaction we share from building this software together.

<img src="https://cloud.githubusercontent.com/assets/188426/12854271/bd778e3c-cc06-11e5-88b5-7abdf0f518f0.png" width="300" height="300">

**Comment by necolas** [comment]
I don't think a css file needs a logo :)

**Comment by Yeswanth-JG** [comment]
logo looks promising & nice..!
