### ISSUE TITLE
Normalize.css v4 Roadmap

### ISSUE THREAD

**Issue by jonathantneal** [necolas/normalize.css#510]
Thank you to all the contributors across this planet moving the web forward. Normalize.css is now used in production by tens of millions of sites and applications, and it’s about to hit 20,000 stars. Good on you, internet.

The [CHANGELOG.md] in the master branch has major improvements and is now about as long as it was for v3. After musing on these changes, I propose a few remaining goals for Normalize.css v4.

TLDR;

1. **Add regression testing**. Include visual diffs in each new release.
2. **Dictate all normalizations**. Confirm what every normalization does by browser and version.
3. **Choose a semver strategy**. Decide how to version control new releases.

---

##### Add regression testing

Normalize.css releases must be tested across a large matrix of supported browsers and operating systems. While not every developer can or needs to test the nearly ~100 most-used combinations for a change, it would be responsible of us to provide a *visual diff*  before any new release as a kind of visual changelog. I’m looking to you all for solutions that would allow us to test our [browser support stack].

##### Dictate all normalizations

Each normalization must include any browser and browser version affected by the change. We are humans who quickly forget what [“modern browser”] means. Thankfully, this audit is made easier with the advent of services like [BrowserStack]. If you want to get involved in open source, this is your opportunity. It’s easy — 1. Find a rule in Normalize.css that does not mention a browser *and* version in the comment; 2. Setup a CodePen to test this change and use BrowserStack to identify which browsers and browser versions are affected; 3. update the comment and make a pull request. This would be a huge help to the project so, hey, go add “Normalize.css contributor” to your resume.

##### Choose a semver strategy

[Semver] is a widely accepted method for deciding how version numbers are incremented in a project. It goes `MAJOR.MINOR.PATCH`. In my general opinion; a fallback declaration (like [adding `text-decoration: underline` for browsers that don’t support `text-decoration: underline dotted`]) produces a PATCH release; a normalization for older browsers (like [correcting the duplicate application of `bolder` in Safari 6.0.2]) produces a MINOR release; and almost any other change (like [removing opinionated, non-normalizing styles]) produces a MAJOR release. I’d really appreciate your feedback on this issue, as I would like to add language like this to our documentation.

[CHANGELOG.md]: https://github.com/necolas/normalize.css/blob/02c5c7adbbec1707900fde86068405735c733b42/CHANGELOG.md
[browser support stack]: https://github.com/necolas/normalize.css#browser-support
[“modern browser”]: https://github.com/necolas/normalize.css/blob/v2.1.3/normalize.css#L36-L44
[BrowserStack]: https://www.browserstack.com/
[Semver]: http://semver.org/
[removing opinionated, non-normalizing styles]: https://github.com/necolas/normalize.css/commit/02c5c7adbbec1707900fde86068405735c733b42
[adding `text-decoration: underline` for browsers that don’t support `text-decoration: underline dotted`]: https://github.com/necolas/normalize.css/commit/5304c784ffbd03da265fcbf7bf49f6964cbcfc9c
[correcting the duplicate application of `bolder` in Safari 6.0.2]: https://github.com/necolas/normalize.css/commit/bb55babbd1fc484861398692db06d62a495c8e7d

**Comment by mathiasbynens** [comment]
I agree with the proposed semver approach. :+1:

**Comment by battaglr** [comment]
1. **Add regression testing.** That's not going to be easy (I think); but would be great to have something like that!

2. **Dictate all normalizations.** Excellent idea; It's a good thing that [we have already started heading that way](https://github.com/necolas/normalize.css/blob/v2.1.3/normalize.css#L46-L54).

3. **Choose a semver strategy.** I also agree with the proposed approach.

**Comment by jonathantneal** [comment]
Agreed on all counts.

1. Haven’t come up with a regression automation strategy. Something to continue pursuing.
2. Dictating normalizations has been rocking.
3. Semver is go.

**Comment by jonathantneal** [comment]
I’ll be closing this with a PR for v4 later this evening.
