### ISSUE TITLE
I don't understand monospace, monospace

### ISSUE THREAD

**Issue by corysimmons** [necolas/normalize.css#513]
https://github.com/necolas/normalize.css/blob/master/normalize.css#L239

Could someone explain it?

**Comment by KIPdeKIP** [comment]
[From README.md:](https://github.com/necolas/normalize.css/blob/2bdda84272650aedfb45d8abe11a6d177933a803/README.md#extended-details)

>The `font-family: monospace, monospace` hack fixes the inheritance and scaling
>of font-size for preformated text. The duplication of `monospace` is
>intentional.  [Source](http://en.wikipedia.org/wiki/User:Davidgothberg/Test59).

**Comment by corysimmons** [comment]
Ugh, close this quick before anyone sees what a non-doc-reading jerk I am! :weary:

**Comment by jonathantneal** [comment]
@corysimmons, it’s a long-held frontend tradition to question `monospace, monospace`. Do not feel too bad. I appreciate that you looked over the code.
