### ISSUE TITLE
Add .npmignore

### ISSUE THREAD

**Issue by dcdeiv** [necolas/normalize.css#520]
When you deliver a package via npm you should ignore dev files in the `.npmignore` file. If someone is interested in dev files, he/she/it can clone or download the repo on github.

Here is an example of a `.npmignore` file you should add:

```.npmignore
# We don't care about git as long as we download the package via npm
.gitignore

# We won't change the file. It will be plugged into the page as it is.
# Plus we use preprocessors, newbies don't even know what stylelint is.
.stylelintrc

# We don't have to test anything on travis for the same reason of stylelint.
.travis.yml
```

Pretty easy! The package will be nicer and slimmer!

**Comment by TrySound** [comment]
@dcdeiv `files` field of package.json do the same but as whitelist which is better practice. It's already introduced in https://github.com/necolas/normalize.css/blob/master/package.json#L6

**Comment by jonathantneal** [comment]
Agreed, @TrySound. I did not know it functioned as a whitelist, either. Thanks, @dcdeiv for bringing this up so we could both learn about `files`.
