### ISSUE TITLE
Tag 3x release

### ISSUE THREAD

**Issue by jonathantneal** [necolas/normalize.css#521]
I just noticed there is no tagged releases for Normalize v3. It would be useful to tag https://github.com/necolas/normalize.css/commit/2bdda84272650aedfb45d8abe11a6d177933a803. I’m leaving this here as a reminder to do this later today.

**Comment by battaglr** [comment]
@jonathantneal, what do you mean with "there is no tagged releases for Normalize v3"? I'm probably missing something, but I see [releases](https://github.com/necolas/normalize.css/releases) for [v3.0.0](https://github.com/necolas/normalize.css/releases/tag/3.0.0), [v3.0.1](https://github.com/necolas/normalize.css/releases/tag/3.0.1), [v3.0.2](https://github.com/necolas/normalize.css/releases/tag/3.0.2) and [v3.0.3](https://github.com/necolas/normalize.css/releases/tag/3.0.3).

**Comment by miquelfire** [comment]
I think the issue here is that the format of tags changed, so the 3.x versions are below previous versions. At the very least, change the tags to follow one format.

**Comment by battaglr** [comment]
I totally agree that would be better to use a standar way to name all releases. :+1: to that!

**Comment by jonathantneal** [comment]
@miquelfire, oh my, I thought there were no tags because of that. Should we use the new format or the old format? If the old, should we duplicate the 3x tags?

**Comment by alrra** [comment]
>  the new format or the old format

Note: The main reason why `v` was dropped was because of [Component](https://github.com/componentjs/component) (see: https://github.com/necolas/normalize.css/issues/300#issuecomment-34952397 and https://github.com/necolas/normalize.css/issues/208).

**Comment by jonathantneal** [comment]
Got it. Thanks @alrra!
