### ISSUE TITLE
dfn italic style

### ISSUE THREAD

**Issue by jonathantneal** [necolas/normalize.css#522]
I’m not sure `dfn` needs the italic style, and perhaps it should be removed. I checked for the style in Chrome 16+, Edge 12+, Firefox 4+, IE6+, Opera 12.12+, and Safari 6+. Only Safari ≤ 5.1 is missing the style. The supported browser stack of normalize.css has been Safari 6.

And if it isn’t removed, we should still attach a version number to the comment.

**Comment by battaglr** [comment]
@jonathantneal, sadly, Android stock browser apparently still needs this normalization. Here are some [test results](https://gist.github.com/battaglr/bd7276a135755ce77c4b) —based on BrowserStack.

I'll try to test this on real devices, but I would not merge #532 until we have more results on Android.

**Comment by jonathantneal** [comment]
@battaglr, is there a particular version of Android this affects?

**Comment by battaglr** [comment]
@jonathantneal, not sure, since *BrowserStack* does not inforns the Android version. I'll test on real devices, but I just have a few... help narrowing this down would be much appreciated.

**Comment by jonathantneal** [comment]
Great, we can use it to decide a policy on Android support, https://github.com/necolas/normalize.css#browser-support, as I just noticed there is not one.

**Comment by battaglr** [comment]
Sadly we can't remove this yet.

| OS / Browser                | Test status |
|-----------------------------|-------------|
| Android 6 / Chrome 49       | Pass        |
| Android 5.1 / Chrome 49     | Pass        |
| Android 4 / Chrome 42       | Pass        |
| Android 4 / Default Browser | Not Pass    |

*Test results that confirm or refute this results are more than welcome!*

**Comment by cvrebert** [comment]
Android 5.0 is when the Android Browser (at least the "normal" one, unless the device manufacturer opts for a custom one) [switched to an evergreen update scheme](http://developer.android.com/about/versions/lollipop.html#WebView).
The Browser on older Android versions is buggy and annoying, [but sadly still popular.](http://developer.android.com/about/dashboards/index.html#Platform)
