### ISSUE TITLE
Where is the wiki?

### ISSUE THREAD

**Issue by bgdz** [necolas/normalize.css#523]

**Comment by bgdz** [comment]
Where is the wiki? There's a link to it on the project page, but it looks like the wiki has been disabled.

**Comment by battaglr** [comment]
@bgdz, hi! You can find the documentation in the "[extended details](https://github.com/necolas/normalize.css/blob/master/README.md#extended-details)" section on the [README](https://github.com/necolas/normalize.css/blob/master/README.md).

That said, I couldn't find the link to the Wiki on the [project site](http://necolas.github.io/normalize.css/); but I did find it in the [blog post](http://nicolasgallagher.com/about-normalize-css/#normalize-css-has-extensive-documentation) —@necolas could be possible to update that if you have the time?

**Comment by jonathantneal** [comment]
Nicolas’ blog is not hosted in this repo, so we can let him update it on his own time.
