### ISSUE TITLE
outline : 0  ▶ outline-style: none;

### ISSUE THREAD

**Issue by parapada73** [necolas/normalize.css#524]
I found it in your code

```
a:active,
a:hover {
  outline: 0;
}
```

According to reference outline property is 

> outline-color outline-style outline-width|initial|inherit

Therefore, I'd like to do so in order to avoid any confusion.

```
a:active,
a:hover {
  outline-style: none;
}
```

**Comment by battaglr** [comment]
@parapada73, hi! When using shorthand properties you are defining multiple possible values at once. In this particular case by using `outline: 0` you're implying `outline-width: 0`.

In any case, if you would like to be explicit you could suggest using `outline-width: 0` instead, but I think `outline: 0` is clear enough and shorter than the equivalent.

**Comment by kafeltz** [comment]
outline:0 is clear but outline is tricky about shortcuts
