### ISSUE TITLE
New release due?

### ISSUE THREAD

**Issue by brendon** [necolas/normalize.css#526]
There currently aren't any v3 release tags. Just wondering if you'd be interested in creating one? I'm looking at pulling through to https://github.com/markmcconachie/normalize-rails/issues/17#issuecomment-195927561 but we wanted to be sure we're using a stable version.

**Comment by alrra** [comment]
> There currently aren't any v3 release tags

@brendon See: https://github.com/necolas/normalize.css/releases.

**Comment by brendon** [comment]
Ah I see, the tags drop down shows the 3.x tags at the bottom because you dropped the v off at that point :)

**Comment by brendon** [comment]
Would you be interested in releasing a new version that incorporates the removal of the table styles?

**Comment by alrra** [comment]
> Would you be interested in releasing a new version that incorporates the removal of the table styles?

Cc @jonathantneal :arrow_up:

**Comment by jonathantneal** [comment]
I will prioritize the next release for this week. I was managing the 3.2x release of sanitize.css. Let’s connect on gitter https://gitter.im/necolas/normalize.css to be sure we’ve checked off all the things before the release. :)

**Comment by jonathantneal** [comment]
I am on track for a release tomorrow. All remaining issues are appropriately tagged. We’ll see what has time to get in, but regardless, a great v4 release is coming.

**Comment by brendon** [comment]
Thanks @jonathantneal :)
