### ISSUE TITLE
Bower?

### ISSUE THREAD

**Issue by dangelion** [necolas/normalize.css#527]
Could you add to Bower? Or you removed it? Why?

Thanks

**Comment by TrySound** [comment]
Last version still has bower support. But yes it's removed.
https://github.com/necolas/normalize.css/pull/504

**Comment by battaglr** [comment]
Bower —and Component— **explicit support** was removed on 8cfa3e765e0cb55c174657e412430424a9fee97a and discussed on #455.

@jonathantneal, what do you think if we add something like this to the existing docs:

> npm: npm install --save normalize.css
> **Bower: bower install --save https://github.com/necolas/normalize.css.git**
> cdnjs
> Download.

By doing this we could avoid the creation of new issues on this topic and at the same time inform how to install it.

Happy to PR!

**Comment by jonathantneal** [comment]
I would very much like that. I’d also like to discuss this in the gitter room https://gitter.im/necolas/normalize.css where we can quickly hash out our hit list for getting 4 out the door this week.
