### ISSUE TITLE
'main' field dropped from package.json with 4.0.0

### ISSUE THREAD

**Issue by pekim** [necolas/normalize.css#542]
It was added with 947b1ae124cc987848262b6513242c83348a733d, but has been dropped with 3123b8e9f5923fd06e4eeb9e0727b7cc42fd94f6. This means requiring `normalize.css/normalize.css` instead of just `normalize.css`.

Is this an intentional change?

**Comment by battaglr** [comment]
@pekim, hi! It was indeed an intentional change, see #441. Is this causing you any troubles?

**Comment by viko16** [comment]
Oh, I think we should notice this change on README.

**Comment by battaglr** [comment]
@viko16, you're right, we should add that, but to the [CHANGELOG](https://github.com/necolas/normalize.css/blob/master/CHANGELOG.md), not the README. I've opened #551 to do that. Thanks!

**Comment by maxdow** [comment]
It breaks with webpack or it's now needed to add a custom configuration. 

Typical example when you want to extract vendors modules : 

var vendors = Object.keys(require("../package.json").dependencies);

var webpackConfig = {
  entry : {
    app : [path.resolve(__dirname, "../src/app.js")],
    vendors : vendors,
  },
  plugins : [
    new webpack.optimize.CommonsChunkPlugin({
      name :"vendors",
      filename : "vendors.bundle.js"
    }),
...
}

We now need to add a custom alias ( resolve.alias ) property to the correct file.

Is it a definitive change ?

**Comment by jonathantneal** [comment]
Would it be more appropriate to add `main` back to `bower.json`?

**Comment by pekim** [comment]
It's not really a big deal, and easy enough to deal with. It's more that it came as a slight surprise that's all.

**Comment by jonathantneal** [comment]
@pekim, for some time bower.json had been dropped from the project, but a release containing the change had not been made. We brought it back before the v4 release. This is why I’m mentioning restoring the file. @TrySound might have additional advice, as he was involved in our bringing it back.

**Comment by jonathantneal** [comment]
This has been re-added via #564

**Comment by benoitvallon** [comment]
Since you decided to re-add it (which is nice I think), would it be possible to publish a 4.0.1 on npm please? Thanks
