### ISSUE TITLE
Bad vertical alignments

### ISSUE THREAD

**Issue by Yapaslfeu** [necolas/normalize.css#543]
Bad vertical alignments for image and range inputs
Should include the following:

[type='image'],
[type='range'] {
	vertical-align: middle;
}

**Comment by jonathantneal** [comment]
What makes them bad? Are they inconsistent among the browsers?

**Comment by Yapaslfeu** [comment]
In fact, all browsers use a baseline alignement but the visual effect is not consistent (sometimes a label appears in the middle, sometimes at the bottom, depending of the browser).

**Comment by jonathantneal** [comment]
@Yapaslfeu, if this is a visual quirk, would you please put together a quick test page on [CodePen](https://github.com/necolas/normalize.css/blob/master/CONTRIBUTING.md#bug-reports) for this?

**Comment by Yapaslfeu** [comment]
I don't know how to use CodePen
Here is the code to see it:
<html>
<head>
<style>
input {
	width: 300px;
	padding: 50px;
}
</style>
</head>
<body>
Image: <input type="image" /><br/>
Range: <input type="range" />
</body>
</html>

**Comment by gguillotte** [comment]
[CodePen based on the example from @Yapaslfeu](https://codepen.io/oznogon/pen/bpWMeg)

**Comment by jonathantneal** [comment]
> `vertical-align: middle` should [have been called] `text-middle` because it's not really in the middle.
> — [Incomplete List of Mistakes in the Design of CSS ](https://wiki.csswg.org/ideas/mistakes)

I agree that the `middle` alignment looks better in this particular case, but that doesn’t mean it would look better in every case, and every browser already treats these elements the same.

### mac_osx_10 8_safari_6 2_1024x768_chromeless
![mac_osx_10 8_safari_6 2_1024x768_chromeless](https://cloud.githubusercontent.com/assets/188426/14061438/935999c0-f356-11e5-84fc-94656e199087.png)

### mac_osx_10 11_safari_9_1024x768_chromeless
![mac_osx_10 11_safari_9_1024x768_chromeless](https://cloud.githubusercontent.com/assets/188426/14061436/9357834c-f356-11e5-86d3-d18d0c42c4e1.png)

### windows_7_64-bit_firefox_45_1024x768_chromeless
![windows_7_64-bit_firefox_45_1024x768_chromeless](https://cloud.githubusercontent.com/assets/188426/14061437/9358aa42-f356-11e5-8c7a-2d5d794c4875.png)

### windows_7_64-bit_google_chrome_49_1024x768_chromeless
![windows_7_64-bit_google_chrome_49_1024x768_chromeless](https://cloud.githubusercontent.com/assets/188426/14061439/9359ed26-f356-11e5-8c91-d5257d41bbd6.png)

### windows_7_64-bit_internet_explorer_10_1024x768_chromeless
![windows_7_64-bit_internet_explorer_10_1024x768_chromeless](https://cloud.githubusercontent.com/assets/188426/14061435/93578fe0-f356-11e5-96af-4c6ca586bb7f.png)

### windows_7_64-bit_internet_explorer_11_1024x768_chromeless
![windows_7_64-bit_internet_explorer_11_1024x768_chromeless](https://cloud.githubusercontent.com/assets/188426/14061440/935c152e-f356-11e5-9bf4-bff53fa51bc4.png)

### windows_7_internet_explorer_8_1024x768_chromeless
![windows_7_internet_explorer_8_1024x768_chromeless](https://cloud.githubusercontent.com/assets/188426/14061441/935efbfe-f356-11e5-83bd-c031fbc8ec5f.png)

### windows_7_internet_explorer_9_1024x768_chromeless
![windows_7_internet_explorer_9_1024x768_chromeless](https://cloud.githubusercontent.com/assets/188426/14061442/93629462-f356-11e5-8964-3d58d1432d94.png)

### windows_7_opera_32_1024x768_chromeless
![windows_7_opera_32_1024x768_chromeless](https://cloud.githubusercontent.com/assets/188426/14061443/93644910-f356-11e5-83af-5382ae601090.png)

### windows_10_microsoft_edge_1024x768_chromeless
![windows_10_microsoft_edge_1024x768_chromeless](https://cloud.githubusercontent.com/assets/188426/14061444/9366f778-f356-11e5-9e02-362670ed7827.png)
