### ISSUE TITLE
No pointer cursor on file and image inputs

### ISSUE THREAD

**Issue by Yapaslfeu** [necolas/normalize.css#544]
Should have a pointer cursor hover file and image inputs in all browsers:
[type='file'],
[type='image'] {
	cursor: pointer;
}
[type='file']::-webkit-file-upload-button {
	-webkit-appearance: button;
	cursor: pointer;
}

**Comment by jonathantneal** [comment]
Thanks for pointing this out. Would this pointer also apply to the text field of a file input?

**Comment by thierryk** [comment]
Please read [this discussion](https://github.com/necolas/normalize.css/issues/371). The idea was to actually **remove** [such styling](https://github.com/necolas/normalize.css/issues/371#issuecomment-60203961) from normalize.css

**Comment by jonathantneal** [comment]
@thierryk. Yikes. Unfortunately, this was closed without a change to the code to actually remove these items. I’m sorry to have missed this. It was my original intention to remove all opinionated styles in v4, but there was concern that it was bad practice. See #518

**Comment by Yapaslfeu** [comment]
I understand for the cursor.
Indeed, the -webkit-appearance: button; should be kept as the file select button is rounded on Mac, the same inconsistency you fixed on line 332 (* 2. Correct the inability to style clickable types in iOS.)

[type='file']::-webkit-file-upload-button {
-webkit-appearance: button;
}

**Comment by jonathantneal** [comment]
Excellent. I will look into this!

**Comment by thierryk** [comment]
@jonathantneal I think "removing the default `margin` from `body`" may be the "exception qui confirme la règle". But note that this styling has no impact on UX&mdash;which is not the case of `cursor` on controls.
