### ISSUE TITLE
Bad image input box-sizing

### ISSUE THREAD

**Issue by Yapaslfeu** [necolas/normalize.css#545]
Image input is wider than other input fields, as box-sizing is set as content-box
Should be:
[type='image'] {
	box-sizing: border-box;
}

**Comment by jonathantneal** [comment]
Is the content box sizing consistent across all browsers?

**Comment by Yapaslfeu** [comment]
You're right, it's consistent across all browsers, it's just not consistent with other input fields…

**Comment by jonathantneal** [comment]
I would say this is then a job for [sanitize.css](https://github.com/10up/sanitize.css), but it already makes all things `border-box`. :)
