### ISSUE TITLE
Textarea is not consistent in Safari with other browsers

### ISSUE THREAD

**Issue by visicode** [necolas/normalize.css#548]
Should add:
textarea {
	-webkit-appearance: textfield;
}

**Comment by jonathantneal** [comment]
If you would like me to review this, please include an example.

**Comment by Yapaslfeu** [comment]
In fact, the main problem is about the border color: in Safari, input fields have a lighter border color than textareas, unlike other browsers which apply the same border color for both fields.

**Comment by jonathantneal** [comment]
Have you tested this in Chrome, Edge, and Safari?

**Comment by Yapaslfeu** [comment]
Yes
The modification can only be seen in Safari and Chrome on Mac (not on iPhone).
For Chrome on Windows, textarea (default) and textfield modes seams to be treated the same way…
For Edge, button (default) and textfield seams to be treated the same way too…

**Comment by jonathantneal** [comment]
Form controls are unique to operating systems, which is why normalize.css generally avoids targeting them, as doing so introduces an opinionated default.

There is a project specifically for adding these kinds of opinionated defaults to forms. https://github.com/visicode/formalize.css
