### ISSUE TITLE
Focus ring is not consistant anymore in Firefox

### ISSUE THREAD

**Issue by Yapaslfeu** [necolas/normalize.css#549]
Setting the moz-focusing for button and input fields made the focus ring different for select and textarea fields
Should add too:
select:-moz-focusring,
textarea:-moz-focusring {
	outline: 1px dotted ButtonText;
}

**Comment by jonathantneal** [comment]
Actually, Firefox uses a different outline style between buttons and text inputs. These also vary by OS. It’s best not to mess with focus outlines, so I will limit the normalizations to buttons. I traced the blame for this change back to the [early days of normalize.css](https://github.com/necolas/normalize.css/commit/b9ad7aea10819c766aec31268db7eea9ad7487c5) (note the IE hacks and CSS expressions, ouch).
