### ISSUE TITLE
Too many things appear as buttons

### ISSUE THREAD

**Issue by OscarMarshall** [necolas/normalize.css#554]
I'm using [material-ui](https://github.com/callemall/material-ui) and their menu-item component makes use of a ```<span [...] type=button>```. As a result of the changes in 9a3b1b3, my menu-items now look like big buttons. Is there a reason the selectors were widened or can we revert these changes?

**Comment by battaglr** [comment]
@OscarMarshall, hi! Thanks for reporting this. AFAIK `type="button"` is not a valid attribute for that element, it's only valid for [`<input>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) and [ `<button>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button) elements. The proper way to indicate that a `<span>` it's a button or will behave like one should be [`role="button"`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_button_role).

Regarding the reason, was to lower the specificity, see #438.

Maybe you could open an issue in their repo about this.

**Comment by jonathantneal** [comment]
Sorry for my delayed response, but @battaglr addressed this concern. We use `type` attribute values only valid on `<button>` and `<input>`. 

FWIW, the `type` attribute may be used on `<menu>` with a value of `context` or `list`, and it may be a valid mime-type when used on `<embed>`, `<object>`, `<script>`, `<source>`, or `<style>`. The usage of `<span type="button">` is not valid HTML.
