### ISSUE TITLE
Suggestion: Switch Safari support to "last two" to match other browsers

### ISSUE THREAD

**Issue by gouch** [necolas/normalize.css#555]
What's the reason for starting Safari support at version 6 instead of "last two" like the other modern browsers? I'm not aware of it being a special case highly used old version (like IE 8) and it doesn't even show up on a typical usage chart ([1](http://gs.statcounter.com/#desktop-browser_version_partially_combined-ww-monthly-201502-201602-bar), [2](http://www.netmarketshare.com/report.aspx?qprid=3&qpaf=&qpcustom=Safari+6.0&qpcustomb=0)).

An immediate benefit: Dropping 6 support would mean simpler [`b, strong` rules](https://github.com/necolas/normalize.css/blob/master/normalize.css#L119-L135).

**Comment by battaglr** [comment]
@gouch, hi! Thanks for bringing this up! We could certainly take a closer look to the numbers. That said, now I'm inclined to agree with @jonathantneal —please, see [#482 (comment)](https://github.com/necolas/normalize.css/issues/482#issuecomment-174851077)— when he says that very low percentages could mean lots and lots of users, and just saving a few bytes may not be worth it to drop support.

**Comment by gouch** [comment]
@battaglr Thanks for the link. I'm not really arguing to drop Safari 6 to save bytes, though, just wondering why it doesn't follow the "last two" rule used for other modern browsers.

**Comment by battaglr** [comment]
@gouch, I think I didn't explain myself correctly. I do think that you are asking a good question. Maybe we could take a closer look to the numbers about Safari versions usage to see what's going on, and wait for feedback from the community.

**Comment by jonathantneal** [comment]
If we switch to a modular source where each normalization and test is independent then people can build their own versions of normalize.css, and it would be our primary responsibility that the compiled version is tested and works across a very generous spread of widely-used browsers. To that end — and I said this in another thread — if normalize.css powers tens of millions of websites, and each of those sites gets just 1 visitor, then a lonely 1% of our audience already represents about one-hundred-thousand people. With the modular approach, you could build a version with support closer to what Google offers, following the last 2 approach, or perhaps take that and add additional support for Internet Explorer browsers based on your own support needs.
