### ISSUE TITLE
select with multiple attribute shows options from overflow

### ISSUE THREAD

**Issue by joshknutson** [necolas/normalize.css#562]
in version 4 around line 277 it says to have overflow:visible for select fields, only appears to be an issue in Google Chrome, checked on Version 50.0.2661.49 beta-m and Version 49.0.2623.87 m 

[Fiddle Link](https://jsfiddle.net/Emergence/d8eovbvk/)
[Screen shot](http://screencast.com/t/q5Ci8fkg)

Firefox, Internet Explorer, and Edge were fine.

**Comment by joshcartme** [comment]
Just saw this myself, at least in Chrome (I didn't look at other browsers) adding:
```
select[multiple] {
    overflow-x: hidden;
    overflow-y: auto;
}
```
seemed to fix the issue

**Comment by authcode** [comment]
Version 4.0.0 also breaks select elements in Chrome that present as scrolled list boxes using the **size** attribute. This can be fixed with something like:
`select[multiple], select[size] {
overflow-x: hidden;
overflow-y: auto;
}`

**Comment by jonathantneal** [comment]
The issue with the original change was that `overflow` was being checked, and not `overflow-x` and `overflow-y` individually. A fix is in.
