### ISSUE TITLE
CDNJS 4.0.0.min breaks Windows 7 Firefox Inspector

### ISSUE THREAD

**Issue by maxpower9000** [necolas/normalize.css#565]
CSS rules are not shown inside Firefox Inspector upon inspecting elements. 
Loading normalize.min.css from [cdnjs](https://cdnjs.cloudflare.com/ajax/libs/normalize/4.0.0/normalize.min.css).
No issues when using 3.3.2.min or 4.0.0(non min).

**Update**
It seems to be a Firefox issue.
Testing with _Firefox DevEd 47.0a2_ produces the bug
Testing with _Firefox 44_ does not

**Comment by battaglr** [comment]
@maxpower9000, thanks for reporting this! I can't reproduce this on Firefox DevEd 47.0a2 (OS X). Are you still having this issue?

**Comment by maxpower9000** [comment]
@battaglr. Thanks for testing. Yes, I can still produce the same phenomenon.

**BUT!** 
The project also uses [-prefix-free](https://github.com/LeaVerou/prefixfree). It seems to be the reason for the issue. After taking out _-prefix-free_ the inspector works.

So you're off the hook :)
