### ISSUE TITLE
webpack require failed.  lost "main": "normalize.css" option in package.json

### ISSUE THREAD

**Issue by chzhuo** [necolas/normalize.css#567]
version:4.0.0

"require('normalize.css')" not work in webpack. Because forget ' "main": "normalize.css" ' in package.json.

**Comment by zlargon** [comment]
I got the same problem with v4.0.0.
The issue has been fixed in https://github.com/necolas/normalize.css/commit/375ff10793431738e80dab8063f66757598c91f8.
Hope to see the updated version on NPM as soon as possible.

**Comment by battaglr** [comment]
@chzhuo, @zlargon, thanks for reporting this!

@jonathantneal, could be possible to publish v4.1.0 on npm to solve this? At the risk of going off-topic, I'm suggesting v4.1.0 since I beilive that ab3abb6d36cf3cd66e22faeec65dcef1196ba1c1 deserves a *minor* release. Before doing that we need to update the CHANGELOG. I can create the PR if you prefer.

**Comment by jonathantneal** [comment]
Yes, a minor release is forthcoming. I just need a review on the fix for the `select` bug. Then it’s time to release 4.1.0.

**Comment by denizdogan** [comment]
IMO, this fix deserves a quick patch release, seeing how it's virtually unusable to so many in its current state on NPM.

**Comment by emirotin** [comment]
There's a fix for webpack config explained here: https://github.com/react-toolbox/react-toolbox/issues/446#issuecomment-208543374

**Comment by zlargon** [comment]
Here's another way to fix the issue in entry point: https://github.com/zlargon/my-web-app-boilerplate/commit/80b53a347ba60e0611eae3712fd2505c042575a4

**Comment by emirotin** [comment]
That works if you import the module explicitly. But in some cases it's a
peer dependency of one of your project dependencies that you cannot control.

**Comment by zlargon** [comment]
@emirotin You're absolutely right, thanks! :smile:

**Comment by jonathantneal** [comment]
![image](https://cloud.githubusercontent.com/assets/188426/14463503/46f5671c-0099-11e6-8c57-0b030f24270e.png)

The `main` property has been restored in v4.1.

**Comment by kaptajnen** [comment]
Adding the main field means it now no longer works with browserify+parcelify. Any ideas on how to support both browserify and webpack at the same time?
