### ISSUE TITLE
No uniform aspect of "file select" buttons after normalization

### ISSUE THREAD

**Issue by Yapaslfeu** [necolas/normalize.css#570]
In the same way you are setting -webkit-appearance:button in line 299, i think you should do the same for the "select file" button present in file fields, in order to keep a uniform aspect between all fields in Safari:

[type='file']::-webkit-file-upload-button {
-webkit-appearance: button;
}

**Comment by jonathantneal** [comment]
This does help with Chrome and Safari, but not iOS Safari. I’ll definitely consider it.
