### ISSUE TITLE
Inconsistent background color for file and color inputs

### ISSUE THREAD

**Issue by Yapaslfeu** [necolas/normalize.css#578]
File inputs have a grey background color on Edge and IE, and Color inputs have a grey background color on Chrome and Firefox, while those fields have a transparent background on all other browsers i could try.

Should add:
`[type="color"],`
`[type="file"] {`
`	background-color: transparent;`
`}`

**Comment by slavanga** [comment]
Setting the background-color to transparent makes both input types look uglier than the default in Edge. The file input will even stay grey.

https://jsfiddle.net/g3fcs33a/1/

**Comment by Yapaslfeu** [comment]
Your right, the look changed!
Try to put a 50px padding around those fields to see the inconsistent grey background, but my solution may not be perfect neither…

**Comment by jonathantneal** [comment]
I’m not interested taking away from the default UI styles of inputs. We would end up slowly styling forms completely. In general, we should avoid messing with any colors.
