### ISSUE TITLE
Correct the inability to style select fields on Mac OS

### ISSUE THREAD

**Issue by Yapaslfeu** [necolas/normalize.css#579]
Not sure you get my #572 message:

> It must be [corrected], or you will not be able to apply any style to select fields on Mac OS!!!
This is a low level problem and is exactly the same than the one you're fixing in line 294 "2. Correct the inability to style clickable types in iOS."

> Why not using this then:
`select {`
`    -webkit-appearance: menulist-button;    /* Mac Aqua off */`
`}`
`@supports (-ms-accelerator:true) {`
`    select {`
`        -webkit-appearance: menulist;    /* Revert to default for Edge */`
`    }`
`}`

**Comment by jonathantneal** [comment]
Closed via #587

**Comment by Yapaslfeu** [comment]
This is not a patch to make forms looking the same on every browser, as explain in #587 
This is patch to correct an annoying problem in Mac OS only not letting stylize combo boxes!

You correct the same problem in line 294 "2. Correct the inability to style clickable types in iOS."
Why not for combo boxes then?

**Comment by battaglr** [comment]
@Yapaslfeu, could you please provide a test case to helps us understand? It's always useful to have something to look at, like a [CodePen](http://codepen.io/), [JSFiddle](https://jsfiddle.net/); even screenshots are very useful. Thanks!

**Comment by Yapaslfeu** [comment]
Combo box with `font-size: 30px;` and `height: 100px;` without changing the -webkit-appearance:
![capture d écran 2016-07-02 a 18 58 43](https://cloud.githubusercontent.com/assets/2444125/16541605/5a66dfa0-4087-11e6-8ebe-5552d94c9ebe.jpg)

The same combo box after setting -webkit-appearance to menulist-button:
![capture d écran 2016-07-02 a 18 59 33](https://cloud.githubusercontent.com/assets/2444125/16541627/a4a3c286-4087-11e6-90e8-6c4c90144548.jpg)

One cannot change the select field appearance without first removing the Mac Aqua effect!
To remove it, the best way is touching the -webkit-appearance, but can be done too changing the background color or the border attribute…

**Comment by Yapaslfeu** [comment]
You're doing exactly the same in line 306 when setting `-webkit-appearance: button;` to buttons for iOS and Safari! Without it, buttons will not be "stylizable", except if setting the background color or the border attributes.

Here under, the same buttons both with `font-size: 30px;` and `height: 50px;` attributes, but the bottom one with your `-webkit-appearance: button;` property set:
![capture d ecran 2016-07-02 a 19 27 15](https://cloud.githubusercontent.com/assets/2444125/16541711/03710a50-408b-11e6-895d-5bc18a0fc020.jpg)
