### ISSUE TITLE
Optgroups don't inherit font family and font style in Firefox

### ISSUE THREAD

**Issue by Luchian** [necolas/normalize.css#581]
The font family and font style are not inherited by optgroup labels and options within an optgroup in Firefox 45 (probably happens in some older versions too). The screenshot below demonstrates this using the normalize.css UI tests page:

![optgroup-firefox](https://cloud.githubusercontent.com/assets/550271/14500420/bd3e9486-01aa-11e6-8f6a-127a3f8103a5.jpg)

This can be fixed by setting `optgroup {font-family: inherit; font-style: inherit;}` and `optgroup option {font-style: inherit;}`.

**Comment by Luchian** [comment]
After further digging it seems that adding `optgroup {font: inherit; font-weight: bold;}` is a better solution since only the font size is set to be inherited.

**Comment by slavanga** [comment]
It looks like the optgroup was removed by mistake in 0c90242.
