### ISSUE TITLE
Search input inconsistent on iPhone

### ISSUE THREAD

**Issue by Yapaslfeu** [necolas/normalize.css#582]
The -webkit-appearance: textfield is not enough to remove the border rounding on iPhone.
Strangely, the rounded borders are correctly set only when entering into the field (iPhone bug).

A working solution is to use the none appearance, which has no side effects as far as i tried:
`[type="search"] {`
`	-webkit-appearance: none;`
`}`

**Comment by battaglr** [comment]
@Yapaslfeu, as you know, setting `-webkit-appearance: none;` will destroy all *default* styles, and that's not the goal of this project.

Is this happening on all versions of Safari Mobile? If this is a bug, is there a bug report that we can see? Thanks!

**Comment by jonathantneal** [comment]
Closed via #587

**Comment by Yapaslfeu** [comment]
This is not a patch to make forms looking the same on every browser, as explain in #587 
This is a patch to correct a bug on iPhone not fully supporting your line 392 `-webkit-appearance: textfield;` patch!

But @battaglr is right: this is a display bug which should be fixed by Apple on iPhones

**Comment by Yapaslfeu** [comment]
The search field once opening the web page on iPhone:
![img_5644](https://cloud.githubusercontent.com/assets/2444125/16541507/4d75667e-4085-11e6-860d-034eebf9d824.jpg)

The search field once putting the cursor into:
![img_5647](https://cloud.githubusercontent.com/assets/2444125/16541504/31c84572-4085-11e6-9df2-19094a5e0f57.jpg)

Then, the search field remains with the same aspect even moving the cursor to another field, till the web page is refreshed…
