### ISSUE TITLE
Try making forms looking the same once for all!

### ISSUE THREAD

**Issue by Yapaslfeu** [necolas/normalize.css#587]
I know you will not agree (#578), but i believe that the only solution to get rid of all those inputs style problems we have is to completely remove all browsers specific UI style, so all forms will look exactly the same on every browser!

And this can be done easily, starting from setting the same border and background color to all fields!
I know it's arbitrary colors but one can change them easily, reducing the problem to a simple design question!
The result is that we don't have to think about browsers specifics anymore and only concentrate on design, forgetting about compatibility/consistency.

Here is the main part of the code i use for that (without the focus and hover parts):
`button,`
`input:not([type="range"]):not([type="file"]):not([type="image"]),`
`select,`
`textarea {`
`	border: 1px solid #c0c0c0;`
`}`
`[type="color"] {`
`	background-color: #fff;`
`}`
`[type="file"] {`
`	background-color: transparent;`
`}`
`button,`
`html [type="button"],`
`[type="reset"],`
`[type="submit"] {`
`	background-color: #e1e1e1;`
`}`
`::-webkit-file-upload-button {`
`	border: 1px solid #c0c0c0;`
`	background-color: #e1e1e1;`
`}`
`::-ms-browse {`
`	border: 1px solid #c0c0c0;`
`}`

**Comment by Yapaslfeu** [comment]
Here is a demo with the full CSS i use: [https://codepen.io/Yapaslfeu/pen/aNGLQy]

**Comment by jonathantneal** [comment]
This would be much more useful in something like [sanitize.css](https://github.com/10up/sanitize.css),. normalize.css should not get into overriding OS styling.

**Comment by Yeswanth-JG** [comment]
Hi. @Yapaslfeu  ...

Normalize preserves default styling. It standardizes the things and maintain the consistency. Changing the presentation is not intended.

**Comment by battaglr** [comment]
@Yapaslfeu, as others already said this doesn't seem suitable for this project.

*Off-topic:* as I can see from the many issues that you have opened over time, you know a lot about forms and browsers inconsistencies; would be awesome if you created a project with all that (please, provide a link if you do)!

**Comment by jonathantneal** [comment]
Agreed.

**Comment by visicode** [comment]
@battaglr, thank you for your suggestion!
I just create the new project **_formalize.css_** intended to normalize forms:
https://github.com/visicode/formalize.css

It has to be included right after normalize.css.
This is a very first version and any help will be appreciated to improve it…

**Comment by battaglr** [comment]
@visicode, awesome! Thanks for sharing. I'm sure the two projects would benefit from each others. 😀
