### ISSUE TITLE
Consider updating the GitHub project description

### ISSUE THREAD

**Issue by battaglr** [necolas/normalize.css#600]
Currently the GitHub project description says:

> A collection of HTML element and attribute style-normalizations

While in the README:

> A modern alternative to CSS resets

It would be nice to update the description using the last one.

**Comment by jonathantneal** [comment]
I’m not able to update the GitHub project description. Thankfully, it’s super minor. :) Shall I close this, or would you like to see an update to the README?

**Comment by battaglr** [comment]
@jonathantneal, oh, I like the new description better, so let's keep the README as it is. I'm closing this since it's just a small detail. :wink:
