### ISSUE TITLE
npm install --save normalizecss does not install newest version

### ISSUE THREAD

**Issue by gitowiec** [necolas/normalize.css#605]
Calling npm install --save normalizecss does not install 4.2.0, instead 3.0.0,
please fix it

**Comment by alrra** [comment]
> npm install --save normalizecss

@gitowiec Should be `normalize.css`, not `normalizecss`.

**Comment by jonathantneal** [comment]
I believe @ben-ng and @chrisdickinson maintain the mirror-ish modules `normalize-css` and `normalizecss` on npm. It seems they’re both out-dated at the moment, but they average about 5k downloads a month. I ran into an issue with one of these recently when a co-worker hit me up about updating the modules, only to discover they were using one of these.

Ben and Chris, if you can keep ’em up to date, awesome! If you wanna add me as a collaborator, I’ll do my best to see they are always up to date.

**Comment by lrsjng** [comment]
@jonathantneal currently `npm install normalize.css` resolves a `package.json` with the correct `4.2.0` but the head comment in the actual `normalize.css` file says it's `4.1.1`..

**Comment by sriksm** [comment]
@lrsjng same issue with bower as well. In both cases (npm n bower) showing 4.2.0 but the downloaded the 4.1.1 version

**Comment by deivisonrpg** [comment]
Same here, 4.1.1 version on npm

**Comment by jonathantneal** [comment]
5.0.0 has been published. Sorry about the confusion with 4.2.0. Use `npm install normalize.css` or contact the maintainers of those other packages to see them updated. Thanks!
