### ISSUE TITLE
Bower install does not work

### ISSUE THREAD

**Issue by dlewand691** [necolas/normalize.css#608]
When running the bower install (bower install --save normalize-css), getting this error:

`bower EINVALID      Name must be lowercase, can contain digits, dots, dashes, "@" or spaces
`

Thoughts?

**Comment by ogiansouza** [comment]
Hello @dlewand691 try again, now using:
`bower install --save normalize.css`

**Comment by jonathantneal** [comment]
Yes, please use `bower install --save normalize.css` (note the dot).
