### ISSUE TITLE
SVG 100vh height in older webkit browsers

### ISSUE THREAD

**Issue by renatorib** [necolas/normalize.css#611]
Older webkit browsers, like Safari from iPhone 5s (idk exactly which version is) uses a default of 100vh for some embedded objects, and svg.

You can see here:
https://bugs.webkit.org/show_bug.cgi?id=82489
http://stackoverflow.com/questions/7570917/svg-height-incorrectly-calculated-in-webkit-browsers

My workaround was setting `svg { max-height: 100% }`

**Comment by jonathantneal** [comment]
With the resolution coming somewhere between 2 and 4 years ago, I don’t think this would be something we would want to introduce to normalize.css, unless there were tests that showed it had zero negative effect on all supported browsers.
