### ISSUE TITLE
Mobile browser considerations

### ISSUE THREAD

**Issue by wamoyo** [necolas/normalize.css#613]
The documentation doesn't say whether or not normalize does anything with mobile browsers. Some clarity would be great. Please do let me know, if I totally missed something that's there.

**Comment by wamoyo** [comment]
I stand correctly... There is this line: 'It supports a wide range of browsers (including mobile browsers)...'

**Comment by battaglr** [comment]
@wamoyo, hi! Thanks for opening this. It's a good idea to review this topic, since we don't explicitly mention any mobile browser. Would you mind reopening this? Thanks! 😀

**Comment by wamoyo** [comment]
Yeah, no problem.

**Comment by jonathantneal** [comment]
I use [xbt](https://crossbrowsertesting.com/) to test the two-most-recent handheld-sized and tablet-sized Android and iOS browsers. How might we package that notice?

**Comment by battaglr** [comment]
@jonathantneal, I would start by iOS Safari and Android default browser.

**Comment by wamoyo** [comment]
The two main ones will be iOS Safari, and Chrome for Android. The old Android browser is almost gone. It just seems to be Chrome now.

**Comment by jonathantneal** [comment]
Okay, we will explicitly mention these.

**Comment by jonathantneal** [comment]
Resolved via https://github.com/necolas/normalize.css/commit/4411f95888e1eacf6dbba66e8d63bb648eafd6fa
