### ISSUE TITLE
th and font-weight: bold

### ISSUE THREAD

**Issue by gavsiu** [necolas/normalize.css#616]
I just happen to notice that there is no th tag in normalize.css. Do all the supported browsers have th font-weight set to bold?

**Comment by brlodi** [comment]
I can confirm from source that the supported versions of Safari, Chrome, Firefox, and IE all specify `font-weight: bold`. As Opera is Blink-based like Chrome I would be shocked if it were different (and I just confirmed as much with a minimal HTML test). I don't have access to Edge to test at the moment, but it would be a trivial check there as well.

In fact in my perusal I noticed that the rendering engines with defaults defined in CSS all seem to share *exactly* the same stanza for the `th` element.
