### ISSUE TITLE
4.2.0 release on website

### ISSUE THREAD

**Issue by josh18** [necolas/normalize.css#619]
It looks like 4.2.0 has been released but the [website](https://necolas.github.io/normalize.css/) still has 4.1.1, is this just an oversight?

**Comment by mckibbenta** [comment]
Additionally, if one navigates to, for example, https://cdnjs.cloudflare.com/ajax/libs/normalize/4.2.0/normalize.css, the first line still notes 'v4.1.1'.

**Comment by battaglr** [comment]
Apparently by mistake the [tag for v4.2.0](https://github.com/necolas/normalize.css/blob/4.2.0/normalize.css) doesn't have the proper version number in the comment, but is in fact v4.2.0. This was later fixed in this commit: 255074ef4a761fa7e77689cbebe6e5fb70d529c2.

**Comment by jonathantneal** [comment]
Thanks! This has been updated with https://github.com/necolas/normalize.css/pull/624
