### ISSUE TITLE
 Property -webkit-text-size-adjust is an unknown vendor extension

### ISSUE THREAD

**Issue by nandlal-tjm** [necolas/normalize.css#620]
W3C CSS validator says Property -webkit-text-size-adjust is an unknown vendor extension 
```
html {
	font-family: sans-serif;
	-webkit-text-size-adjust: 100%;
	-ms-text-size-adjust: 100%;
}
```
I got warning from W3C CSS validator.

**Comment by battaglr** [comment]
You —and the W3C validator— are right, [this property is *non-standard*](https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust); but we need to use it to [solve a problem](https://github.com/necolas/normalize.css/blob/master/normalize.css#L6). 😀
