### ISSUE TITLE
body min-height 100%

### ISSUE THREAD

**Issue by hugabor** [necolas/normalize.css#622]
It would be nice to have the following:

    html { height: 100% }
    body { min-height: 100% }

This would standardize the size of the "html", stretching it to 100% of the viewport height, and obviously, the body would then stretch to 100% of the viewport height and would extend with content.

This is one of the first things that I always add to my css, especially when working with non-scrolling pages or web-apps.

It helps with centering content in the middle of the viewport, and I don't believe it interferes with other types of layouts.

In fact, it kind of makes a `body { background-color }` function more like what the css reveals (because in reality, the background color gets set to the entire page, not just "within the bounds" of the `body` element).

I am not aware of how mobile browsers behave with this, although I do know that it worked fine on iOS Safari (I used it in conjunction with `preventDefault` scrolling/zooming for an unmovable page).

**Comment by thierryk** [comment]
@hugabor 

I don't think the rules you suggest adding fit the goals of this repo. 

From the `README`:

> What does [normalize] do?
> 
> Preserves useful defaults, unlike many CSS resets.
> Normalizes styles for a wide range of elements.
> Corrects bugs and common browser inconsistencies.
> Improves usability with subtle modifications.
> Explains what code does using detailed comments.

As a side note, you say:

> In fact, it kind of makes a `body { background-color }` function more like what the css reveals (because in reality, the background color gets set to the entire page, not just "within the bounds" of the body element). 

Not really. That's only true if there is no `background` on `html` as in this case the specs say to propagate the background of `body` to the entire viewport.

**Comment by hugabor** [comment]
I would argue that this "Improves usability with subtle modifications."

And indeed, the specs do say to propagate the background of `body`, however this isn't revealed by the *syntax* (which, although it shouldn't be a problem if one's read the specs, can be confusing).

**Comment by jonathantneal** [comment]
While it might be a useful developer default in some situations, this change would not be a normalizing behavior between the browsers, nor an adherence to the spec.
