### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by brendon** [necolas/normalize.css#630]
I'm keen to get the changes in HEAD (particularly the fixes to `font: inherit` on form elements) through into the `normalize-rails` gem. Our policy is that we don't release a new gem until those changes are tagged in a release.

Would you mind releasing a new version? :)

**Comment by jonathantneal** [comment]
Thanks for your patience. 5.0.0 has been released!

**Comment by brendon** [comment]
Thanks for that! :D
