### ISSUE TITLE
normalize.min not in bower

### ISSUE THREAD

**Issue by ferreiro** [necolas/normalize.css#632]
Hello guys,

I've just downloaded normalize.css using bower. But in bower_components/normalize.css does not appear the minified version. Is this because is not possible to include it on bower or because you don't want to suppor the minied version?

Best.
Jorge.

**Comment by Toddses** [comment]
#410

**Comment by jonathantneal** [comment]
What’s mentioned in #410 (thanks @Toddses), and it’s much cleaner for us all to leave compiled files **off** the repository. If you’re using bower or npm to import normalize, I would imagine you have a build process that could combine and minify all these files for you.

**Comment by ferreiro** [comment]
@Toddses Thank you!
@jonathantneal Ah okey! I use gulp for build tasks. So according to you're response I'll then create a new pipeline to minify the normalize for production. Thanks for your response ;)

**Comment by Toddses** [comment]
@ferreiro If you're using Sass in that build process, you can just `@import` normalize straight from your node modules and it will become a part of your core css file.

**Comment by ferreiro** [comment]
@Toddses Thanks for your response! You mean to do @include 'test.css' in the main file for the sass? If this is the scenario, I've just tryed it and does not work.

**Comment by Toddses** [comment]
@ferreiro You need to `@import "test.css"`. Check out the Import section here http://sass-lang.com/guide

**Comment by josephfusco** [comment]
I might be out of the loop with recent versions of sass but as far as I'm aware using `@import` on a regular .css file does not treat it like a partial but rather how regular CSS does.

**Comment by Toddses** [comment]
I'm using gulp-sass and `@import`ing normalize.css and it's treating it like a partial. But I did make a mistake above, you'd want to `@import "test";`. No extension.
