### ISSUE TITLE
Hard to find documentation about issues addressed in normalize

### ISSUE THREAD

**Issue by Volker-E** [necolas/normalize.css#634]
Some of the rules have been part of normalize for quite a while, for example

``` css
button,
input { /* 1 */
  overflow: visible;
}
```

Over time it's getting harder to find documentation about the issues behind the solution. The closest in this case for me were:
- http://edskes.net/ie/ie8overflowandexpandingboxbugs.htm
- http://jehiah.cz/a/button-width-in-ie

`blame` isn't of help here, History is really hard to search in-depth.

It should be considered to have descriptive examples without and with normalization.

**Comment by battaglr** [comment]
@Volker-E, this is an awesome idea. This would be a lot of work, though.

Do you have an idea in mind on how to do this?

**Comment by barraponto** [comment]
I like how [HTML5 Boilerplate does it](https://github.com/h5bp/html5-boilerplate/blob/master/src/doc/html.md). 
Something along the lines of [StyleDocco](https://jacobrask.github.io/styledocco/styledocco/examples/bootstrap/docs/buttons.html) be good too.

**Comment by battaglr** [comment]
@barraponto, I think that doing something similar to [H5BP](https://github.com/h5bp/html5-boilerplate/blob/master/src/doc/html.md) is a great idea! What do you think, @jonathantneal?

**Comment by jonathantneal** [comment]
I agree with the original issue. I do like the scalability normalize.css, so I would lean toward putting this documentation in a Markdown file. This can happen aside any release on virtually any timeframe, so I’d love to see a PR.

**Comment by jonathantneal** [comment]
PR never came. Closing this.
