### ISSUE TITLE
Remove iOS input shadow

### ISSUE THREAD

**Issue by kvetoslavnovak** [necolas/normalize.css#635]
Possible solutions http://stackoverflow.com/questions/23211656/remove-ios-input-shadow

**Comment by battaglr** [comment]
@kvetoslavnovak, hi! Using `appearance: none` is not a good fit for this project. 😞

**Comment by kvetoslavnovak** [comment]
I agree. So do you think that `box-shadow: none !important;
` is better solution?

**Comment by jonathantneal** [comment]
This is outside the scope of normalize.css,  but you may want to raise the issue on sanitize.css. Also, a less destructive solution may be `background-clip: padding-box;`.
