### ISSUE TITLE
Any plans to make Normalize eyeglass compatible?

### ISSUE THREAD

**Issue by ashleynolan** [necolas/normalize.css#638]
I was just wondering if there was any plan to make the NPM module of Normalize compatible with [Eyeglass](https://github.com/sass-eyeglass/eyeglass)?

I’ve seen there’s a [sass version of normalize](https://www.npmjs.com/package/normalize-scss) which is eyeglass compatible, but all I really want to pull into my projects is the straight up Normalize CSS, so was wondering if this was planned, or whether it would be worth me forking the repo and making a module that does this.  Alternatively, I’d be happy to submit a PR to add this, if it would be something that you’d want to look to include.

Thanks for all the great work on the project.

**Comment by battaglr** [comment]
@ashleynolan, it's really hard to keep track of all these tools coming up. What changes would be necessary to support this?

**Comment by ashleynolan** [comment]
I’ll try and get something working in a fork so that I can see exactly what needs to be done and link to it as an example.  Will post back here once I’ve done that (will be in the next couple of days)

**Comment by battaglr** [comment]
@ashleynolan, no need to code anything at this point. I just wanted to know if is we need to include a new file, an entry on the `package.json` or something else.

**Comment by ashleynolan** [comment]
You can do it in a couple of ways, but the easiest is by including a few lines in the `package.json`.

Includes adding "eyeglass-module" as a keyword and then a set of eyeglass options ([like this](https://github.com/zurb/foundation-sites/blob/develop/package.json#L102)).

Then after adding these, it should be possible to install Normalise via NPM and include it in a Sass build by just referencing `@import normalise` (or whatever import keyword you give it in the `package.json`).

**Comment by battaglr** [comment]
@ashleynolan, great that's great info, thank you! @jonathantneal, what do you think about this?

**Comment by kevva** [comment]
I wonder why authors to these tools are trying to make module authors adapt to them rather than the other way.

**Comment by battaglr** [comment]
@kevva, I wonder the same thing... 😞

**Comment by jonathantneal** [comment]
@ashleynolan, are we able to add JUST the "eyeglass-module" keyword to make it compatible? If it requires more, do let me know the additional code you’ll need.

**Comment by jonathantneal** [comment]
Hey all, I’ll be closing this issue if we’re unable to get clearer instructions or an answer to my question by the 1st of January. Just trying to keep things moving along.

**Comment by ashleynolan** [comment]
@jonathantneal Sorry for not replying – should have kept on top of this.

From what I’ve done in the past, it involves adding the keyword and then having to add a couple of lines [such as this](https://github.com/TryKickoff/kickoff-grid.css/blob/master/package.json#L75).  These point to the directory of the module, the name you want people to import the module as and the version of eyeglass supported.

**Comment by jonathantneal** [comment]
A PR for this could be made. I have not seen movement on this, though, so I am closing it.
