### ISSUE TITLE
Can provide sass version of it?

### ISSUE THREAD

**Issue by chinajoy** [necolas/normalize.css#645]
Can provide sass version of it?

**Comment by Toddses** [comment]
You can easily import normalize.css as if it were a regular Sass partial.

```
@import "../../node_modules/normalize.css/normalize";
```

**Comment by garrettw** [comment]
Alternatively, there is a native Sass fork at [JohnAlbin/normalize-scss](https://github.com/JohnAlbin/normalize-scss)
