### ISSUE TITLE
Normalize styles for invalid inputs

### ISSUE THREAD

**Issue by barraponto** [necolas/normalize.css#648]
Bringing up the issue from https://github.com/twbs/bootstrap/issues/21323
Firefox now applies styles to invalid inputs under very specific cases: 

> * If the control does not have focus, and the value is invalid, apply this pseudo-class.
> * If the control has focus, and the value was valid (including empty) when it gained focus, do not apply the pseudo-class.
> * If the control has focus, and the value was invalid when it gained focus, re-validate on every keystroke.
> * If the element is required, the preceding rules apply only if the user has changed the value or attempted to submit the form.

Read more: https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-ui-invalid

**Comment by barraponto** [comment]
I don't think there is an equivalent pseudo-class in other browsers. So we're basically limited to remove the styles if we want to normalize the behavior across browsers.

**Comment by PerseusTheGreat** [comment]
Hmmmm...
Defining normalized styles for an input in specific situations, like validating, getting focus, ...!
I just thought about normal appearance of form inputs.

May be we should develop a normalize.js to override these anomalies...

**Comment by jonathantneal** [comment]
Unfortunately, at this time, we can’t target these scenarios, so we can’t normalize these scenarios.
