### ISSUE TITLE
Lists <ul> and <ol> with left-floated images render completely differently in Blink & Gecko

### ISSUE THREAD

**Issue by stroobandt** [necolas/normalize.css#650]
This is a feature request.
I have been using `normalize.css` for many years without any issue.

Recently, I tried something new: Floating inline images to the left inside lists (both `<ul>` and `<ol>`).
This may sound a bit crude, but when you are using Markdown for content writing, there are very little formatting options…

Anyhow, results look OK in Gecko (Firefox) and Goanna (Pale Moon) based browsers, with the list item markers/numbers still more left than the left-floated item images. I guess, this is also the result one would intuitively expect.

However, I was shocked to see that Blink (Chromium, Vivaldi) and Webkit based browsers **show a completely different result.** With these browser engines, the left-floated images are rendered completely to the left.

Worse, **list item markers/numbers do not respect image right-margins.** Item markers are stuck to the right of the images. Still worse, **double digit item numbers even overlap the images.**

Here are a couple of pages where these effects can be seen:
http://hamwaves.com/antenna.books/en/index.html#myfavourites
http://hamwaves.com/stealth/en/index.html#publications

In my humble opinion, these unexpectedly huge rendering differences would warrant normalization.

**Comment by thierryk** [comment]
I do not think there is a way to normalize this behavior since browsers are styling markers very differently and authors do not have access to those elements... yet.

I found the problem interesting though and tried to come up with a solution/hack: [Displaying list markers before floated elements](http://codepen.io/thierry/pen/ZBdRBg).

Please let me know if that does not work for you.

**Comment by jonathantneal** [comment]
Leaving this open a week to see if it *can* be normalized, but that seems unlikely. Thanks for the workaround, @thierryk.

**Comment by stroobandt** [comment]
@thierryk Thanks Thierry, for proposing so quickly and diligently a workaround. Nonetheless, I detected three problems with the workaround.

1. `content: counter(item) ". ";` requires a non-breaking space after the period, as shown here. However, since this is a CSS `content` statement, the non-breaking space can **not** be introduced the usual way by typing `&nbsp;`. Instead, use the [keyboard entry method of your editor](https://en.wikipedia.org/wiki/Non-breaking_space#Keyboard_entry_methods). Doing so, this issue is solved.
2. The list items are not properly indented when they wrap beyond the left floated images (see attached screenshots). This is not as easy as adding some `padding-left` because double digit ordered list items would require more padding. So, this issue remains to be solved for `<ol>`.
No indentation:
![no_indentation](https://cloud.githubusercontent.com/assets/1105595/21555302/338951ce-ce17-11e6-847e-b5f5b5feca8f.png)
versus desired indentation:
![indentation](https://cloud.githubusercontent.com/assets/1105595/21555304/3be7983a-ce17-11e6-9bd8-aebd09bb36c9.png)
3. The workaround also requires some amount of negative padding to mimic the default list placement (also visible in above screenshots). Perhaps, this is also a key towards solving issue 2?

@jonathantneal You would expect `normalize.css` to deal with such browser inconsistencies, but of course, it needs to be doable. With `<ul>` is see no issues; It is only `<ol>` where the variable indentation remains a problem to be solved.

**Comment by stroobandt** [comment]
And now for something different; **Could it be that we are dealing with a Blink bug?**
Mind you, I am not having this issue with [Prince XML](https://princexml.com).

With [`list-style-position: inside;`](http://www.w3schools.com/cssref/pr_list-style-position.asp), I can get Firefox to render a nicer version of the Chromium Blink result. Unfortunately, this does not apply the other way around with `list-style-position: outside;`.

**Comment by thierryk** [comment]
@stroobandt thanks for the feedback. It helped me made a few changes that should address your concerns. Check the [update section](http://codepen.io/thierry/full/ZBdRBg/) at the bottom of the page.

> And now for something different; Could it be that we are dealing with a Blink bug?

Actually, I'm afraid that even though we do not like the way things work in Chrome, it appears that's how the specs define the new `::marker` pseudo-element. If the specs do not change then things will look weird in **all** browsers as FF and others behaving like it will need to follow [the specs](https://www.w3.org/TR/css-lists/#marker-pseudo-element):

> Like ::before and ::after, the ::marker pseudo-element can be styled with the full range of CSS properties and values, exactly like a real element. Markers are placed at the beginning of their originating element’s content, before the ::before pseudo-element (if it exists). ::marker pseudo-elements are inline by default, though certain values for list-style-position on the list item can make the marker box positioned, which can have an effect on the computed value of display.

To me, the above says that the marker would be displayed **after** a floated element, with the indentation issue you noted.

**Comment by stroobandt** [comment]
@thierryk Great results with your updated workaround! I now get identical results over all browsers and this without much CSS overhead. Thanks!

@jonathantneal I think this is worthwhile to have in `normalize.css`. It looks completely backward compatible to the casual user and will remain largely unnoticed (this is what we want). Please, note: The `padding-left`, `width` and `margin-right` lines in Thierry's `example-4` are not required for the general case.

**Comment by stroobandt** [comment]
I almost forgot: I noticed the tiniest of discrepancies in both the size (a breath smaller) and placement of the bullet symbol in `<ul>` of the workaround versus the default unordered bullet list. It is hardly noticeable and is probable due to a text scaling browser engine glitch. I corrected this by increasing `font-size: 108%;` in `ul li: before`.

**Comment by thierryk** [comment]
@stroobandt things are not that simple...

For example, `padding-left` is necessary if you want to make sure the markers always appear&mdash;as they could be clipped if their containing block was styled with `overflow:hidden`. The hack also requires to style the list items with `position:relative` (to make sure the markers are properly positioned) which influences how elements stack and also creates a containing block that will be used for reference by nested positioned box. Finally, this hack relies on the `::before` pseudo-element which authors could be using for something else.

In my opinion, such hack should be something authors would onboard only when facing that *specific issue with floats*. I really think that including this in a library would create more problems than it solves.

**Comment by stroobandt** [comment]
@thierryk Yes, I understand. The ways of the W3C standardisation are by times mysterious…
I noticed [the document you referenced](https://www.w3.org/TR/css-lists/#marker-pseudo-element) is still a working draft. Obviously, they appear not to have thought about all the `<ol>` and `<ul>` use cases. Perhaps an opportunity for you to chime in there?

**Comment by thierryk** [comment]
I've already [asked David Baron](https://twitter.com/thierrykoblentz/status/813941642298212352) from Mozilla. I'm really curious to see how those different engines will end up implementing `::marker` because according to David:

> I think ::marker has to be compatible with existing list marker behavior

but there is no common behavior across major browsers. The author of that Draft is Tab Atkins though, so somehow it makes sense that `::marker`&mdash;as specced today&mdash;aligns with how Chrome deals with markers.

**Comment by stroobandt** [comment]
@thierryk Great to see you are involved to that extent and waging the right CSS battle. Thanks for your great work & a happy new year!
Keep us in the loop here with your progress.

**Comment by thierryk** [comment]
Thanks @stroobandt Happy New Year to you too!

**Comment by jonathantneal** [comment]
Since this requires some curious hacks, I’m going to leave this out. Great discussion, though.
