### ISSUE TITLE
why is the generic font family name repeated in code, kbd, samp style

### ISSUE THREAD

**Issue by Kareem-Badr** [necolas/normalize.css#651]
code,
kbd,
samp {
  font-family: monospace, monospace; /* 1 */
  font-size: 1em; /* 2 */
}

**Comment by thierryk** [comment]
From the [README}(https://github.com/necolas/normalize.css/blob/2b6082d43a9d5f2584e77e69cd145c87ad6103be/README.md#extended-details-and-known-issues):

> The font-family: monospace, monospace hack fixes the inheritance and scaling of font-size for preformatted text. The duplication of monospace is intentional. [Source](https://gist.github.com/413930).

**Comment by Kareem-Badr** [comment]
@thierryk thank you for explaining.
