### ISSUE TITLE
German Translation of Nicolas Gallagher's article

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [necolas/normalize.css#668]
Please add this link to your official website in section Translations (http://nicolasgallagher.com/about-normalize-css/):
https://www.saskialund.de/normalize-css-was-ist-das/

It contains the german translation (Deutsche Übersetzung) of Nicolas Gallagher's article: http://nicolasgallagher.com/about-normalize-css/

Thank you!

P.S.: Tried to reach out via Twitter several times, however I didn't receive any reply. My translation is  online since June 2015 ;)
See tweet on translation release: https://twitter.com/SaskiaLund/status/609730925551874049

**Comment by jonathantneal** [comment]
Thanks @s-a-s-k-i-a. You’ll want to reach out to @necolas directly if you want your article linked to his blog. I’ve pinged him here if you two want to discuss this further.
