### ISSUE TITLE
Safari's web inspector reports -webkit-text-size-adjust can't be 100%

### ISSUE THREAD

**Issue by deirdresm** [necolas/normalize.css#674]
This is on Version 10.1 (12603.1.30.0.34) on El Capitan (current shipping).

Can be seen on http://desamo.staging.wpengine.com (with Safari).

![screen shot 2017-05-12 at 5 12 25 pm](https://cloud.githubusercontent.com/assets/10251429/26020710/bf5424a8-3736-11e7-9a22-1f9a854c4774.png)

**Comment by deirdresm** [comment]
Actually, looks like this was added in a version of WebKit that's not yet shipping. See: https://bugs.webkit.org/show_bug.cgi?id=151805 Therefore, I'll close this.

**Comment by alwillis** [comment]
The message "The value '100%' is not supported for `-webkit-text-size-adjust` only shows up on macOS; it’s fine for the iOS version of Safari.
