### ISSUE TITLE
Why no universal selektor

### ISSUE THREAD

**Issue by janstieler** [necolas/normalize.css#675]
Hi,

why have the normalize.css no universal selector with margin and padding 0?
I have at Chrome several times problems with selectors like  -webkit-padding-start: as example from Chrome.

Cheers

**Comment by bardiharborow** [comment]
Normalise **preserves useful defaults**, and hence does not intrusively reset margin and padding execpt where it is considered useful. You may want to look at using a more heavy duty CSS reset if you need it for your use-case.

**Comment by simonsmith** [comment]
@janstieler See the README under 'What does it do' - https://github.com/necolas/normalize.css#what-does-it-do

One reset package that builds on normalize is [suitcss-base](https://github.com/suitcss/base)

**Comment by necolas** [comment]
Thanks for the answers everyone

**Comment by janstieler** [comment]
Hi,
Thanks for your answers. I thought the problem with the chrome browser css is falling under “… and common browser inconsistencies”.
@simonsmith thanks for the package link.

Cheers

PS: I don't understand why I got thumbs down. In germany we say, there are no stupid questions, only stupid answers.

**Comment by garrettw** [comment]
[ot] @janstieler - in the USA many people also say that, but unfortunately some people still disagree with it.
