### ISSUE TITLE
Add link to postcss-normalize

### ISSUE THREAD

**Issue by ai** [necolas/normalize.css#679]
Normalize.css is great. But it could be even better if we will remove unnecessary rules based on target browsers (like Autoprefixer does).

And @jonathantneal did this project [postcss-normalize](https://github.com/jonathantneal/postcss-normalize)!

@necolas what do you think if we add link to this project to Normalize.css README? I think your users will be happy to find more way to use Normalize.css.

**Comment by ai** [comment]
@necolas any comments?

For example, we could add some option for `postcss-normalize` to choice original Normalize.css or @jonathantneal mode should be used.

I understand your feelings, but few lines of CSS is not a reason to not be polite with people who are even out of conflict (like me) ;).

**Comment by necolas** [comment]
No, thanks.

**Comment by ai** [comment]
It was really rude
