### ISSUE TITLE
Use System UI Fonts for Form Elements

### ISSUE THREAD

**Issue by calvinjuarez** [necolas/normalize.css#689]
The following browsers are using (or attempting to use) system fonts for the major form elements.  Setting `font-family: sans-serif;` on any of them changes the display.

- **Safari 10.1.1** on Mac has `font-family: -apple-system;` under the selector `input, textarea, keygen, select, button`.
- **Chrome 58.0.3029.110** on Mac has `font: 11px system-ui` under the selector `input, textarea, select, button `.
- **Firefox 53.0** on Mac is a bit more complex, but the internal inspector includes `font-family: -moz-use-system-font;` in the expansion of `font: -moz-field;` (inputs), `font: -moz-button;` (buttons), and`font: -moz-list;` (selects).  (Textareas use Courier on Firefox.)

Compare: https://github.com/necolas/normalize.css/blob/master/normalize.css#L240-L249

Since I've only tested on my Mac, my recommendation at the moment would be changing [line 245](https://github.com/necolas/normalize.css/blob/master/normalize.css#L245) to the following.

```
font-family: -apple-system, BlinkMacSystemFont, sans-serif;
```

But further research is probably a good idea (specifically on Windows—especially Edge—and Android) before a PR is opened, I'd say.

---

My test html looked like this.

```html
<button>button</button>
<input value="input">
<select>
	<option>option</option>
	<optgroup label="optgroup">
		<option>option</option>
		<option>option</option>
	</optgroup>
</select>
<textarea>textarea</textarea>
```

**Comment by mvasilkov** [comment]
I second this very much. In modern browsers, can use `system-ui` (https://www.chromestatus.com/feature/5640395337760768).

**Comment by mvasilkov** [comment]
Since this feature is very unlikely to be added here, a shameless plug: https://github.com/mvasilkov/systematize
It's basically normalize.css with some improvements to typography, coming from this repo's pull requests mostly. WIP.

**Comment by necolas** [comment]
The font family is inherited now
