### ISSUE TITLE
Consider removing  `monospace`, `monospace` hack

### ISSUE THREAD

**Issue by ntwb** [necolas/normalize.css#695]
Historically this has been reported as [duplicate / double monospace font](https://github.com/necolas/normalize.css/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20monospace) at the time of writing 13 times, this issue is not about that, this is about actually removing it as Normalize should no longer require it:

Per https://github.com/necolas/normalize.css/issues/519#issuecomment-197131966

> Browsers using **Blink**, **Gecko**, and **WebKit** reduce the size of `monospace`. Therefore, the `monospace,monospace` fix applies to **Android ≤ 6, Chrome ≤ 49, Firefox ≤ 45, iOS ≤ 9, Opera 15-35**, and **Safari 5-9**. The fix does not work for **Safari ≤ 4**.

> Browsers using **Presto** and **Trident** treat `monospace` normally. Therefore, the `monospace,monospace` fix is not required for **Edge 12-13, Internet Explorer 8-11, Opera ≤ 12.15**, and **Windows Phone ≤ 8.1**.

Based on browser usage here: https://caniuse.com/usage-table:

* Android ≤ 6: 2.01% (This is based on ≤ 5, there's no data on v6 /shrug)
* Chrome ≤ 49: 1.41%
* Firefox ≤ 45: 0.43%
* iOS ≤ 9: 0.09%
* Opera 15-35: 0.27%
* Safari 5-9: 0.23%

Browser usage that is affected by this issue is pretty low, what would the threshold be for this to be considered to no longer be required by Noormalize?

**Comment by Frogging101** [comment]
I believe that the version numbers given were just the latest releases that existed at the time (the comment was posted on March 16, 2016), rather than hard upper bounds on which versions are affected. As of Firefox 55.0.1, `font-family: monospace` still behaves differently from `font-family: monospace, foo`; the former being displayed smaller.

**Comment by Aaronius** [comment]
I'm in Chrome 60 and it seems to me that the `monospace,monospace` hack isn't even working. My `pre` element still gets a computed font size of 13px while regular font size is 16px. I see that this comment mentions that the monospace fix applies to older versions of Chrome:

> Browsers using Blink, Gecko, and WebKit reduce the size of monospace. Therefore, the monospace,monospace fix applies to Android ≤ 6, Chrome ≤ 49, Firefox ≤ 45, iOS ≤ 9, Opera 15-35, and Safari 5-9. The fix does not work for Safari ≤ 4.

But what about newer versions of Chrome?

**Comment by chharvey** [comment]
I also can attest to this as the `monospace, monospace` hack still fixes the bug *(? or feature?)* in Chrome v61 for macOS Sierra. The browser versions in https://github.com/necolas/normalize.css/issues/519#issuecomment-197131966 should be updated.

**Comment by necolas** [comment]
Chrome for macOS is one popular browser that still needs this
