### ISSUE TITLE
website won't center 7.0.0

### ISSUE THREAD

**Issue by caprinohub** [necolas/normalize.css#699]
body {
			max-width: 900px;
			margin: 0 auto;
			background-color: grey;
		}

**Comment by caprinohub** [comment]
firefox 55
chrome 60

**Comment by bronzehedwick** [comment]
This issue is not related to normalize. See this minimal example in codepen: https://codepen.io/bronzehedwick/pen/rGBdBg

**Comment by caprinohub** [comment]
Whitout normalize it works ok

**Comment by dutchenkoOleg** [comment]
Why just not use div for center?

**Comment by garrettw** [comment]
@caprinohub Make sure you have normalize.css linked above/before your other CSS. If normalize is after yours, it won't work.

**Comment by necolas** [comment]
What @garrettw wrote sounds like a plausible explanation
