### ISSUE TITLE
Normalize won't remove dotted outline from links

### ISSUE THREAD

**Issue by Venthe** [necolas/normalize.css#700]
This behaviour differs for Chrome and Firefox;
Wherein clicking and dragging on Firefox will result in link (`<a>` tag) being surrounded by dotted box, on chrome said link will not be marked in any way

Please consider adding to normalize.css@288 another line, to match:

`::moz-focus-inner,`
`button::-moz-focus-inner,`
`[type="button"]::-moz-focus-inner,`
`[type="reset"]::-moz-focus-inner,`
`[type="submit"]::-moz-focus-inner {`
`  border-style: none;`
`  padding: 0;`
`}`

**Comment by tomasz1986** [comment]
This is accessibility related. I would not mess around with anything accessibility related, and especially not by removing the styling. The same is true for default `:focus` styles which differ from browser to browser (and that is not necessarily a bad thing).

**Comment by Florian-R** [comment]
FTR #577 and [probably a lot more](https://github.com/necolas/normalize.css/search?q=outline&type=Issues&utf8=✓)

**Comment by Venthe** [comment]
Understood
