### ISSUE TITLE
Why bother?

### ISSUE THREAD

**Issue by GJG** [necolas/normalize.css#702]
Is it realy neccesary to include this 40px margin in figure? 
/**
 * Add the correct margin in IE 8. ! no one is using this browser anymore !
 */

figure {
  **margin: 1em 40px;**
}

**Comment by russmaxdesign** [comment]
Keep in mind the aim here is to "normalize" i.e. try to get all browsers to display each element consistently. By default, the `<figure>` element has 40px of margin on both sides. This is correctly applied by most browsers, but not by IE8 it seems.

If you don't want this default margin, you can then override it in your own style sheets.

**Comment by GJG** [comment]
OK 
What is the purpose of these extra 40 pixels ?  I usually overwrite it or use other tags.

**Comment by russmaxdesign** [comment]
While I don't know the official reason for this 40px of margin, it was possibly set this way to match with the default style used for the `<blockquote>` element, which has 40px of margin on both sides. The `<blockquote>` is deliberately designed to be indented from the left and edges from the normal flow of text.

You can see them both in their default state here: https://jsfiddle.net/russmaxdesign/qdds6w01/

**Comment by GJG** [comment]
Thank you for your informations.
