### ISSUE TITLE
Suggestion: color datalists

### ISSUE THREAD

**Issue by strider72** [necolas/normalize.css#703]
Firefox and Chrome display Datalists as black on white.  In IE and Edge the list inherits the background color of the parent of the text input.  I would suggest adding this to the normalization:
```
input[list] {
	color: black;
	background-color: white;
}
```

**Comment by tomasz1986** [comment]
Are they really black and white or do they just follow default system colours? In Windows (at least up to Windows 7) you can manually set window background and text colours, and I have a feeling that this may be the case here. If that is the case, then hard coding them to specific colours may not be a good solution.

**Comment by clarcharr** [comment]
This seems to make more sense in sanitize.css; see sanitize.css#140.

**Comment by Volker-E** [comment]
Also the proposed selector does just apply to the `input` element, not the `datalist` itself.
There's [currently no way to style `datalist` elements with CSS only](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Styling_HTML_forms#The_ugly).

**Comment by strider72** [comment]
@Volker-E is correct there's no way to style the list itself in Firefox and Chrome -- but (in my experience) those browsers display it black-on-white; so in the name of "normalization" it makes sense to make IE and Edge follow suit.

@tomasz1986 I don't see an option to change window background color in Windows 10, and Edge is by definition Win10 and up.  Not sure about IE

**Comment by strider72** [comment]
@tomasz1986 You are correct, Firefox and Chrome follow the system window color. (BTW, you can technically change it in Windows 10, but the "how" is stupidly obscure). While this does demonstrate that my suggestion is not as clean as I thought it was, testing showed me a different issue.  If there is no background color specified, Edge uses the Windows Default color for web site backgrounds, which suggests a new addition for Normalize.css:

`body{color:black;background-color:white}`

(I'll post it as a new Issue though.  This is getting a bit drift-y for this thread)
