### ISSUE TITLE
svg:not(:root) specificity is very high

### ISSUE THREAD

**Issue by Kovensky** [necolas/normalize.css#718]
When a document uses normalize.css and inline svg, it's not possible to set an svg element's overflow via CSS through a simple class selector. The overflow value is always overridden by the `svg:not(:root)` override, unless `!important` or other means of artificially raising the specificity of the selector are used.

Maybe this override could be accomplished by doing, instead:

```css
svg {
  overflow: hidden;
}

svg:root {
  overflow: visible;
}
```

This would still require that the user artificially increases the specificity of a selector if they really do mean to override the overflow of an svg root in css, but I suspect that is a much more unlikely use case.

**Comment by garrettw** [comment]
Seems like a smart suggestion. I'll implement it in [Vitals](/garrettw/vitals).
