### ISSUE TITLE
Chrome 64 uses "text-decoration-skip-ink: auto" by default

### ISSUE THREAD

**Issue by AlekseyMartynov** [necolas/normalize.css#722]
https://www.chromestatus.com/feature/5631679087509504

Looks like this:

![ink](https://user-images.githubusercontent.com/4426185/35559894-e61b0d90-05bc-11e8-8755-63cbaf164a9e.png)

If #693 is approved then nothing needs to be changed.
Otherwise `text-decoration-skip-ink: none` can be added to remove the skips.

**Comment by necolas** [comment]
#693 was merged. Thanks

**Comment by missmatsuko** [comment]
I would actually have preferred to set the default text-decoration-skip-ink style on links as 'none' for a couple reasons:

1) Leaving it up to the browser results in a number of different skip behaviours across all modern browsers, which I think defeats the purpose of using normalize. 

Edge, IE, and Firefox won't have any gaps. Chrome uses 'ink' and has gaps on descenders. Safari uses 'skip' and has gaps, but I'm not sure if the behaviour is the same as 'ink' on Chrome.

2) Skipping text decoration on descenders (as Chrome now does by default) can make a single text link look like multiple text links. I think text-decoration-skip can be a nice typographic treatment for non-interactive text, but I don't think it should be applied by default to all links.

![screen shot 2018-03-05 at 4 58 47 pm](https://user-images.githubusercontent.com/17884198/37008783-ac14c11c-2098-11e8-985a-da731aa5ddc9.png)

**Comment by natewind** [comment]
Agreed. Especially since there is already a way to make link underlines look pretty — by using border-bottom:
![image](https://user-images.githubusercontent.com/30814650/38449234-cd8c9852-3a14-11e8-92e2-567dc5d0a069.png)

**Comment by tomasz1986** [comment]
> Agreed. Especially since there is already a way to make link underlines look pretty — by using border-bottom:
`border-bottom` breaks if a link spans over multiple lines though (i.e only the very bottom margin has a border).

**Comment by missmatsuko** [comment]
@tomasz1986 That's not true for inline elements (like anchors are by default). 

This post has some examples of ways to style "underlines":
https://css-tricks.com/styling-underlines-web/

**Comment by tomasz1986** [comment]
> That's not true for inline elements (like anchors are by default).

I stand corrected. I got confused when trying to use `border-bottom` on anchors set to `inline-block` and did not re-test it with default CSS properties.
