### ISSUE TITLE
Yarn package does not exist

### ISSUE THREAD

**Issue by suits-at** [necolas/normalize.css#728]
The yarn package you are linking to in the readme (https://yarnpkg.com/en/package/normalize.css) does not exist. If you follow the link you get the message "Whoa, normalize.css does not exist yet. But that means it is now yours!".

**Comment by Toddses** [comment]
Do any Yarn packages exist? I couldn't find one, and the main Packages link on that site is a blank page. Thought that yarn pulled from the NPM registry...

**Comment by necolas** [comment]
Temporary issue on their side
