### ISSUE TITLE
What does the normalize.min.css.map do?

### ISSUE THREAD

**Issue by gentle-media** [necolas/normalize.css#731]
I know this is not an issue and I've noticed (through a DevTools console error/warning) I have to place this file in the root directory, but I'm curious what does this .map file do?

**Comment by mvasilkov** [comment]
It's called source map. In devtools, you can see the full source code for the minified file when it's present.

**Comment by gentle-media** [comment]
Ah ok... that explains it :) Thanks!

**Comment by garrettw** [comment]
If you don't mind, kindly close this issue if it's resolved.

**Comment by gentle-media** [comment]
Okay... will do!
