### ISSUE TITLE
no such file html5.js

### ISSUE THREAD

**Issue by luojianet** [necolas/normalize.css#734]
This webpage http://necolas.github.io/normalize.css/1.1.3/test.html
a js file status code 404
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

**Comment by coliff** [comment]
That is a very old version of normalize. I suggest to use: http://necolas.github.io/normalize.css/8.0.0/test.html to check instead (doesn't have the error you mention)

**Comment by oles** [comment]
@luojianet If you were comparing old versions to new versions, and you really needed to test version 1.1.3, you could download it yourself and just fix or remove the broken script. (https://github.com/necolas/normalize.css/releases/tag/v1.1.3)

If not, follow @coliff's advice :+1:
