### ISSUE TITLE
Remove webkit padding/margin

### ISSUE THREAD

**Issue by reitermarkus** [necolas/normalize.css#74]
This should be normalized, because it obviously only works in webkit browsers.

-webkit-margin-before: 0;
-webkit-margin-after: 0;
-webkit-margin-start: 0;
-webkit-margin-end: 0;
-webkit-padding-start: 0;

**Comment by nastiatikk** [comment]
Hm… I still see it 2 years later:
![screenshot 2015-03-28 16 21 14](https://cloud.githubusercontent.com/assets/4110509/6883352/a227ad48-d566-11e4-8e30-ce2ee1370786.png)
