### ISSUE TITLE
Bootstrap v4 switches to Reboot

### ISSUE THREAD

**Issue by szepeviktor** [necolas/normalize.css#742]
Does anyone know the reason/s why Bootstrap switched to its fork called *[Reboot](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_reboot.scss#L3-L19)*?

**Comment by mvasilkov** [comment]
@szepeviktor they have different goals, so they end up overriding a number of Normalize styles with their own. Just compare _reboot.scss with normalize.css side by side, you'll see.

**Comment by szepeviktor** [comment]
Thank you.

https://gist.github.com/szepeviktor/22f601da3c6c64b8fa4c473cf02b0723/revisions?diff=split
