### ISSUE TITLE
Normalize blink and marquee

### ISSUE THREAD

**Issue by SoniEx2** [necolas/normalize.css#747]
Apparently those still work in chrome but not in firefox. It would be nice to use CSS3 animations to make them work everywhere.

**Comment by garrettw** [comment]
Oh goodness, surely we don't want to encourage _that_.

**Comment by Toddses** [comment]
Yea I don't imagine anyone will be normalizing obsolete html features. Frankly you shouldn't be using these in your code, Chrome will ultimately remove them. Your code should be as future-proof as possible - using <blink> ensures your code will ultimately break.

**Comment by SoniEx2** [comment]
> Your code should be as future-proof as possible - using ensures your code will ultimately break.

not if normalize.css implements it in CSS

**Comment by Toddses** [comment]
This is anathema to the purpose of normalize.css. If you want a future-proof version of `<blink>`, you should create a custom component. I don't speak for necolas, but I can basically guarantee he's not going to normalize obsolete HTML features.

Personally, and probably this means nothing to you, but I'd avoid using any type of blink for all but the rarest usecases. There's a reason it became an obsolete HTML feature.

**Comment by SoniEx2** [comment]
<blink> works on my text/terminal browser. CSS doesn't.

**Comment by EmmanuelBeziat** [comment]
> There's a reason it became an obsolete HTML feature.

Those tags aren't obsolete HTML feature. Because they have never been part of any HTML version or spec. Ever.

https://www.w3.org/wiki/Html/Elements/marquee 
> No, really. don't use it.

https://www.w3.org/wiki/Html/Elements/blink
> No, really, don't use it. It's simply evil.

So, no. No, no, no and no again. This should **not** ever be put in normalize.css.

**Comment by SoniEx2** [comment]
please?

**Comment by garrettw** [comment]
please don't beg. he basically said no, so just let it die
