### ISSUE TITLE
Aligning breadcrumbs: applying body formatting

### ISSUE THREAD

**Issue by andpiazza** [necolas/normalize.css#756]
My theme built the body of my posts using normalize.css.
How can I apply the same logic to breadcrumbs? I'm using Yoast SEO so it's an id #breadcrumbs. 
They don't appear to have a container class.

**Comment by garrettw** [comment]
Normalize.css does nothing more than tweak browsers' default styles in a way to make them all the same -- which provides a reliable, predictable base for other styles to be built on. It is intended to be a global stylesheet that you load before any other styles. If your theme is somehow applying it only to a certain element on the page, that is an issue of the theme itself, not Normalize.
