### ISSUE TITLE
rtl .pkp_navigation_primary ul 

### ISSUE THREAD

**Issue by ibramimMr** [necolas/normalize.css#759]
an error with value -9999px for (right) position
it's don't make menu shown
i tried to use 0px and it shown up
![2018-08-20_215928](https://user-images.githubusercontent.com/26087511/44363634-fe317700-a4c4-11e8-887b-b3c0c045bc6a.png)
![2](https://user-images.githubusercontent.com/26087511/44363703-35078d00-a4c5-11e8-8b2a-c88718689b9e.png)

**Comment by garrettw** [comment]
That CSS is not part of Normalize.

**Comment by oles** [comment]
@ibramimMr as Garret said - there's nothing in normalize.css related to `right: -9999px`

**Comment by ibramimMr** [comment]
Oh, this is strange of pkp style .
Thanks oles& garret
