### ISSUE TITLE
Provide Normalize as a Template Literal

### ISSUE THREAD

**Issue by joe-bell** [necolas/normalize.css#760]
**Is your feature request related to a problem? Please describe.**

There are a number of existing ports that transform Normalize for use as a template literal/to work with CSS in JS. For example:

1. https://github.com/cssinjs/normalize-jss
2. https://github.com/lestad/styled-normalize

Although it's great to see people going out of their way to make this work for CSS in JS, I'm cautious to install a **non-affiliated** and separately maintained library

**Describe the solution you'd like**

What I propose is an additional `npm prepublishOnly` step that essentially transforms [normalize.css](https://github.com/necolas/normalize.css/blob/master/normalize.css) into a template literal for consumption via `index.js`.

```js
// normalize.css/index.js (proposed)
export default `
  /*! normalize.css v8.0.0 | MIT License | github.com/necolas/normalize.css */
  ...
`
```

For example, if I then wanted to consume Normalize in Emotion, I could use:

```js
// Consuming Normalize
import normalize from 'normalize.css'

injectGlobal`
  ${normalize}
`
```

I understand you're probably keen to keep this as platform agnostic as possible, but I think a lot of CSS in JS users will really benefit from this. Plus as a template string it can be used with any library!

**Describe alternatives you've considered**

I'm not sure of any alternatives for this but I'd be happy to discuss some other options, perhaps an official extension that transforms the dependency rather than hard-coded (like the above examples)?

**Additional context**

Currently spiking a 'full Emotion' example as part of my CSS methodology - "[Smoothie](https://github.com/joebell93/smoothie)"

**Comment by joe-bell** [comment]
Thanks for the feedback @necolas

**Comment by ghost** [comment]
Don't use CSSX. Just because Facebook have started inlining html stuff people are jumping on the bandwagon and going too far.

**Comment by joe-bell** [comment]
> people are jumping on the bandwagon and going too far.

because it's ace @def14nt! 

I _was_ a sceptic just like you, [here are some resources that helped change my mind](https://github.com/joebell93/smoothie#resources-). If you're still unsure please don't hesistate to ping me directly

**Comment by ghost** [comment]
@joe-bell It isn't ace because it's called **bad practice**. OK then, what if you want to edit your css? Instead of just opening a file and editing the content, let's scroll through a *bunch* of JS because Facebook are doing it! It's also called being a sheep.

**Comment by Toddses** [comment]
This probably not the place for a conversation about the merits of CSSX.

**Comment by ghost** [comment]
@Toddses Agreed. Sorry.
