### ISSUE TITLE
Remove Blue Box Outline from Google Chrome

### ISSUE THREAD

**Issue by araligan** [necolas/normalize.css#762]
https://stackoverflow.com/questions/20340138/remove-blue-border-from-css-custom-styled-button-in-chrome

Maybe this one should be included on the normalization. Thanks :)

**Comment by garrettw** [comment]
It's there for accessibility. Check out this article I found that discusses [how to remove outlines without impacting accessibility](https://developer.paciellogroup.com/blog/2012/04/how-to-remove-css-outlines-in-an-accessible-manner/).

**Comment by Malvoz** [comment]
Removing the outline makes it <s>impossible</s> very hard for keyboard-only users to navigate your website, unless you add custom `:focus` styling in a manner where it is clear to the user that an element is focused. 

Take a look at [`:focus-visible`](https://github.com/WICG/focus-visible), it hasn't been finalized [nor implemented widely](https://caniuse.com/#search=%3Afocus-visible) yet so you will have to use the [polyfill](https://github.com/WICG/focus-visible#polyfill).

For more info at MDN:
https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible

**Comment by kotAPI** [comment]
Maybe this issue can be closed now?

**Comment by AlexAldridge** [comment]
Right click the Google Chrome tab.
