### ISSUE TITLE
zero margins...

### ISSUE THREAD

**Issue by AltaTensione** [necolas/normalize.css#764]
Hello, I am using normalize.css for my website. I have a problem for mobile devices because the margin of some sections is 0 and I don't know why. I attach an example here. Can you explain me how to increase the margin? Thank you a lot.

[https://ibb.co/koHfqU](url)

**Comment by garrettw** [comment]
That link doesn't work

**Comment by AltaTensione** [comment]
This is the link of the screenshot: https://ibb.co/koHfqU. Probably i pasted it in a wrong way...

And this is the link of The website: http://bodini.di.unimi.it/

Thank you a lot for your interest.

**Comment by garrettw** [comment]
What is the issue on mobile? I don't see any spacing problems on either link, comparing mobile and desktop.

**Comment by AltaTensione** [comment]
The "issue" is that on mobile screen the text is too near the edges...and I don't know how to reduce this. You can see what I mean from this screen https://ibb.co/hjYwfU. This is what I see from my mobile and from others that I have tested.

**Comment by garrettw** [comment]
Oh ok, I understand now.
The fact is, a lot of sites are designed in a way that rely on zero borders -- plus, it is a way to make all browsers consistent. So if you do want a margin, in your `base.css` just add a `margin` to your `body`.

**Comment by AltaTensione** [comment]
Thank you, now it works as expected.
