### ISSUE TITLE
Suggestion: Remove backtick "`" characters from `normalize.css` comments

### ISSUE THREAD

**Issue by zackkrida** [necolas/normalize.css#789]
The comments in `normalize.css` use backticks as quotes:

https://github.com/necolas/normalize.css/blob/master/normalize.css#L27-L29

When using normalize in JavaScript projects, a lot of css-in-js solutions have you place your css in an _interpolated string_, which are enclosed in backticks. These comments break that behavior.

Not sure if there's a compelling reason to keep them, just thought I would point it out. Thanks!

**Comment by keithort** [comment]
It is most likely there for markdown syntax as that formats anything within the backticks as a code block.

**Comment by Cretezy** [comment]
Also, using an editor to replace 22 characters isn't that much of a hassle.

**Comment by clarfonthey** [comment]
I feel like not escaping your string before moving it into JS is a bug to be fixed, and the markdown formatting here is pretty standard.

Like, not escaping your inputs is a security issue waiting to happen.

**Comment by zackkrida** [comment]
I don't have much stake in this so I'm just going to close it. Maybe this can serve as a reference to css-in-js and normalize.css newcomers in the future.
