### ISSUE TITLE
font-family: monospace, monospace;

### ISSUE THREAD

**Issue by scriptura** [necolas/normalize.css#809]
Bonjour,

Lignes 65 et 108 de la version 8.0.1 on a deux fois la déclaration monospace :

font-family: monospace, monospace;

C'est intentionnel ou j'ai loupé quelque chose ?

**Comment by GaetanBt** [comment]
Hello. Je pense que tu es effectivement passé à côté de [quelques issues](https://github.com/necolas/normalize.css/issues?utf8=%E2%9C%93&q=monospace) qui concernent cette valeur doublée. Il y a des informations plus détaillées dans [celle-ci](https://github.com/necolas/normalize.css/issues/519)

**Comment by scriptura** [comment]
Ok, merci pour le retour. Comme pour l'auteur de l'issue indiquée ce hack avait piqué ma curiosité. Bonne journée !
