### ISSUE TITLE
What is the purpose of duplicate text-decoration under abbr[title]

### ISSUE THREAD

**Issue by mikepjb** [necolas/normalize.css#810]
L87 and L88 both define text-decoration under abbr[title], what's the reason for this? Could it be included in the 'Extended details and known issues' of the README?

https://github.com/necolas/normalize.css/blob/fc091cce1534909334c1911709a39c22d406977b/normalize.css#L88

**Comment by Toddses** [comment]
Here's the PR where it was merged #468 

Seems it was necessary at the time, per the discussion there and in the other linked issues.

**Comment by fisker** [comment]
See https://caniuse.com/#feat=text-decoration
