### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by resynth1943** [necolas/normalize.css#823]
## Remove Google Analytics

If you must have an analytics system, might I suggest either:
- Plausible: https://plausible.io (offers a 50% discount for FOSS projects)
- Goatcounter: https://goatcounter.com
- Matomo: https://matomo.org
- Fathom: https://usefathom.org

These solutions are all well-tested and open-source. This, of course, means they
can be independently audited for privacy and security. Instead of using a proprietary
nonfree system such as Google Analytics, perhaps we could work together to replace
it with something slightly more ethical?

Furthermore, the majority of privacy features in evergreen browsers *block* Google
Analytics from being run. I can not say the same for solutions such as Plausible,
which suggests they are trusted for their privacy by independent persons.

If you need any more information, please contact me!

**Comment by Gaboris** [comment]
I'm curious. How does this connect to Normalize.css?

Does Google offer some kind of a CSS code level Analytics solution that's built in, but isn't referenced or do you mean as a general statement for all online communities?

**Comment by miquelfire** [comment]
I think because the web page uses it.

https://github.com/necolas/normalize.css/blob/3a60304f90870c6087d226f53e02a7523c907a35/index.html#L76

**Comment by resynth1943** [comment]
Yeah, the web page uses it.
