### ISSUE TITLE
I can't find the minimized version

### ISSUE THREAD

**Issue by David263** [necolas/normalize.css#841]
I've been searching and cannot find the minimized version. Is there a good reason for not including it in the download? I want to combine normalize.css with my own styles, but there is too much whitespace and comments for comfortable production use. I'm not sure if this is a bug, a suggestion, or just a question, but the documentation doesn't  seem to address it.

**Comment by garrettw** [comment]
Please search existing issues before reporting new ones.

This was decided against in https://github.com/necolas/normalize.css/issues/4#issuecomment-1783421
