### ISSUE TITLE
Link text color does not show

### ISSUE THREAD

**Issue by PCS2022** [necolas/normalize.css#875]
![image](https://user-images.githubusercontent.com/99375534/153323173-b19c7250-e856-48cf-a0f2-b94854bf360c.png)

**Comment by PCS2022** [comment]
Where the dot is below Log In there is a link to reset the password.

**Comment by miquelfire** [comment]
Sounds like an issue with your CSS code, and not the library. The dev tools in your browser should point you to which CSS rule is setting the color of the link.
