### ISSUE TITLE
Fitting the screen.

### ISSUE THREAD

**Issue by pirrys** [necolas/normalize.css#906]
Hello, I have replaced my reset.css from meyerweb.css with the normalize.css. It has improve , although the page has still to be set at zoom 80%, previously 50%, in order to see the menu. My goal is the zoom at 100% on Android Chrome and Firefox. Any idea how to fix this? 
Thanks.

**Comment by miquelfire** [comment]
Beyond the scope of CSS projects like this.

Do you have the following in your head tag area? `<meta name="viewport" content="width=device-width, initial-scale=1" />`

Everything else will be based on your CSS code.

**Comment by pirrys** [comment]
Sorry I missed that reply, I'll check that out.
Thanks.
